package com.ciobera.fwms.trading.model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 07 19:08:47 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSOrderBookEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FobNo,
        FobDate,
        FobTime,
        FobBS,
        FobLS,
        FobShareClass,
        FobFund,
        FobBroker,
        FobClient,
        FobStock,
        FobStockName,
        FobTicker,
        FobLM,
        FobQty,
        FobPrice,
        FobValue,
        FobMprice,
        FobBqty,
        FobBprice,
        FobAqty,
        FobAprice,
        FobHigh,
        FobLow,
        FobVolume,
        FobBrokerQty,
        FobBrokerCash,
        FobMarginAmt,
        FobOstatus,
        FobEqty,
        FobEprice,
        WmsEnterUid,
        WmsEnterFpc,
        WmsEnterDate,
        WmsLastUpdateUid,
        WmsLastFpc,
        WmsLastUpdateDate,
        WmsApproveUid,
        WmsApproveFpc,
        WmsApproveDate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FOBNO = AttributesEnum.FobNo.index();
    public static final int FOBDATE = AttributesEnum.FobDate.index();
    public static final int FOBTIME = AttributesEnum.FobTime.index();
    public static final int FOBBS = AttributesEnum.FobBS.index();
    public static final int FOBLS = AttributesEnum.FobLS.index();
    public static final int FOBSHARECLASS = AttributesEnum.FobShareClass.index();
    public static final int FOBFUND = AttributesEnum.FobFund.index();
    public static final int FOBBROKER = AttributesEnum.FobBroker.index();
    public static final int FOBCLIENT = AttributesEnum.FobClient.index();
    public static final int FOBSTOCK = AttributesEnum.FobStock.index();
    public static final int FOBSTOCKNAME = AttributesEnum.FobStockName.index();
    public static final int FOBTICKER = AttributesEnum.FobTicker.index();
    public static final int FOBLM = AttributesEnum.FobLM.index();
    public static final int FOBQTY = AttributesEnum.FobQty.index();
    public static final int FOBPRICE = AttributesEnum.FobPrice.index();
    public static final int FOBVALUE = AttributesEnum.FobValue.index();
    public static final int FOBMPRICE = AttributesEnum.FobMprice.index();
    public static final int FOBBQTY = AttributesEnum.FobBqty.index();
    public static final int FOBBPRICE = AttributesEnum.FobBprice.index();
    public static final int FOBAQTY = AttributesEnum.FobAqty.index();
    public static final int FOBAPRICE = AttributesEnum.FobAprice.index();
    public static final int FOBHIGH = AttributesEnum.FobHigh.index();
    public static final int FOBLOW = AttributesEnum.FobLow.index();
    public static final int FOBVOLUME = AttributesEnum.FobVolume.index();
    public static final int FOBBROKERQTY = AttributesEnum.FobBrokerQty.index();
    public static final int FOBBROKERCASH = AttributesEnum.FobBrokerCash.index();
    public static final int FOBMARGINAMT = AttributesEnum.FobMarginAmt.index();
    public static final int FOBOSTATUS = AttributesEnum.FobOstatus.index();
    public static final int FOBEQTY = AttributesEnum.FobEqty.index();
    public static final int FOBEPRICE = AttributesEnum.FobEprice.index();
    public static final int WMSENTERUID = AttributesEnum.WmsEnterUid.index();
    public static final int WMSENTERFPC = AttributesEnum.WmsEnterFpc.index();
    public static final int WMSENTERDATE = AttributesEnum.WmsEnterDate.index();
    public static final int WMSLASTUPDATEUID = AttributesEnum.WmsLastUpdateUid.index();
    public static final int WMSLASTFPC = AttributesEnum.WmsLastFpc.index();
    public static final int WMSLASTUPDATEDATE = AttributesEnum.WmsLastUpdateDate.index();
    public static final int WMSAPPROVEUID = AttributesEnum.WmsApproveUid.index();
    public static final int WMSAPPROVEFPC = AttributesEnum.WmsApproveFpc.index();
    public static final int WMSAPPROVEDATE = AttributesEnum.WmsApproveDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSOrderBookEOImpl() {
    }

    /**
     * Gets the attribute value for FobNo, using the alias name FobNo.
     * @return the value of FobNo
     */
    public Long getFobNo() {
        return (Long) getAttributeInternal(FOBNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobNo.
     * @param value value to set the FobNo
     */
    public void setFobNo(Long value) {
        setAttributeInternal(FOBNO, value);
    }

    /**
     * Gets the attribute value for FobDate, using the alias name FobDate.
     * @return the value of FobDate
     */
    public Timestamp getFobDate() {
        return (Timestamp) getAttributeInternal(FOBDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobDate.
     * @param value value to set the FobDate
     */
    public void setFobDate(Timestamp value) {
        setAttributeInternal(FOBDATE, value);
    }

    /**
     * Gets the attribute value for FobTime, using the alias name FobTime.
     * @return the value of FobTime
     */
    public String getFobTime() {
        return (String) getAttributeInternal(FOBTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobTime.
     * @param value value to set the FobTime
     */
    public void setFobTime(String value) {
        setAttributeInternal(FOBTIME, value);
    }

    /**
     * Gets the attribute value for FobBS, using the alias name FobBS.
     * @return the value of FobBS
     */
    public String getFobBS() {
        return (String) getAttributeInternal(FOBBS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobBS.
     * @param value value to set the FobBS
     */
    public void setFobBS(String value) {
        setAttributeInternal(FOBBS, value);
    }

    /**
     * Gets the attribute value for FobLS, using the alias name FobLS.
     * @return the value of FobLS
     */
    public String getFobLS() {
        return (String) getAttributeInternal(FOBLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobLS.
     * @param value value to set the FobLS
     */
    public void setFobLS(String value) {
        setAttributeInternal(FOBLS, value);
    }

    /**
     * Gets the attribute value for FobShareClass, using the alias name FobShareClass.
     * @return the value of FobShareClass
     */
    public String getFobShareClass() {
        return (String) getAttributeInternal(FOBSHARECLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobShareClass.
     * @param value value to set the FobShareClass
     */
    public void setFobShareClass(String value) {
        setAttributeInternal(FOBSHARECLASS, value);
    }

    /**
     * Gets the attribute value for FobFund, using the alias name FobFund.
     * @return the value of FobFund
     */
    public Long getFobFund() {
        return (Long) getAttributeInternal(FOBFUND);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobFund.
     * @param value value to set the FobFund
     */
    public void setFobFund(Long value) {
        setAttributeInternal(FOBFUND, value);
    }

    /**
     * Gets the attribute value for FobBroker, using the alias name FobBroker.
     * @return the value of FobBroker
     */
    public Long getFobBroker() {
        return (Long) getAttributeInternal(FOBBROKER);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobBroker.
     * @param value value to set the FobBroker
     */
    public void setFobBroker(Long value) {
        setAttributeInternal(FOBBROKER, value);
    }

    /**
     * Gets the attribute value for FobClient, using the alias name FobClient.
     * @return the value of FobClient
     */
    public Long getFobClient() {
        return (Long) getAttributeInternal(FOBCLIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobClient.
     * @param value value to set the FobClient
     */
    public void setFobClient(Long value) {
        setAttributeInternal(FOBCLIENT, value);
    }

    /**
     * Gets the attribute value for FobStock, using the alias name FobStock.
     * @return the value of FobStock
     */
    public Long getFobStock() {
        return (Long) getAttributeInternal(FOBSTOCK);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobStock.
     * @param value value to set the FobStock
     */
    public void setFobStock(Long value) {
        setAttributeInternal(FOBSTOCK, value);
    }

    /**
     * Gets the attribute value for FobStockName, using the alias name FobStockName.
     * @return the value of FobStockName
     */
    public String getFobStockName() {
        return (String) getAttributeInternal(FOBSTOCKNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobStockName.
     * @param value value to set the FobStockName
     */
    public void setFobStockName(String value) {
        setAttributeInternal(FOBSTOCKNAME, value);
    }

    /**
     * Gets the attribute value for FobTicker, using the alias name FobTicker.
     * @return the value of FobTicker
     */
    public String getFobTicker() {
        return (String) getAttributeInternal(FOBTICKER);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobTicker.
     * @param value value to set the FobTicker
     */
    public void setFobTicker(String value) {
        setAttributeInternal(FOBTICKER, value);
    }

    /**
     * Gets the attribute value for FobLM, using the alias name FobLM.
     * @return the value of FobLM
     */
    public String getFobLM() {
        return (String) getAttributeInternal(FOBLM);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobLM.
     * @param value value to set the FobLM
     */
    public void setFobLM(String value) {
        setAttributeInternal(FOBLM, value);
    }

    /**
     * Gets the attribute value for FobQty, using the alias name FobQty.
     * @return the value of FobQty
     */
    public BigDecimal getFobQty() {
        return (BigDecimal) getAttributeInternal(FOBQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobQty.
     * @param value value to set the FobQty
     */
    public void setFobQty(BigDecimal value) {
        setAttributeInternal(FOBQTY, value);
    }

    /**
     * Gets the attribute value for FobPrice, using the alias name FobPrice.
     * @return the value of FobPrice
     */
    public BigDecimal getFobPrice() {
        return (BigDecimal) getAttributeInternal(FOBPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobPrice.
     * @param value value to set the FobPrice
     */
    public void setFobPrice(BigDecimal value) {
        setAttributeInternal(FOBPRICE, value);
    }

    /**
     * Gets the attribute value for FobValue, using the alias name FobValue.
     * @return the value of FobValue
     */
    public BigDecimal getFobValue() {
        return (BigDecimal) getAttributeInternal(FOBVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobValue.
     * @param value value to set the FobValue
     */
    public void setFobValue(BigDecimal value) {
        setAttributeInternal(FOBVALUE, value);
    }

    /**
     * Gets the attribute value for FobMprice, using the alias name FobMprice.
     * @return the value of FobMprice
     */
    public BigDecimal getFobMprice() {
        return (BigDecimal) getAttributeInternal(FOBMPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobMprice.
     * @param value value to set the FobMprice
     */
    public void setFobMprice(BigDecimal value) {
        setAttributeInternal(FOBMPRICE, value);
    }

    /**
     * Gets the attribute value for FobBqty, using the alias name FobBqty.
     * @return the value of FobBqty
     */
    public BigDecimal getFobBqty() {
        return (BigDecimal) getAttributeInternal(FOBBQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobBqty.
     * @param value value to set the FobBqty
     */
    public void setFobBqty(BigDecimal value) {
        setAttributeInternal(FOBBQTY, value);
    }

    /**
     * Gets the attribute value for FobBprice, using the alias name FobBprice.
     * @return the value of FobBprice
     */
    public BigDecimal getFobBprice() {
        return (BigDecimal) getAttributeInternal(FOBBPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobBprice.
     * @param value value to set the FobBprice
     */
    public void setFobBprice(BigDecimal value) {
        setAttributeInternal(FOBBPRICE, value);
    }

    /**
     * Gets the attribute value for FobAqty, using the alias name FobAqty.
     * @return the value of FobAqty
     */
    public BigDecimal getFobAqty() {
        return (BigDecimal) getAttributeInternal(FOBAQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobAqty.
     * @param value value to set the FobAqty
     */
    public void setFobAqty(BigDecimal value) {
        setAttributeInternal(FOBAQTY, value);
    }

    /**
     * Gets the attribute value for FobAprice, using the alias name FobAprice.
     * @return the value of FobAprice
     */
    public BigDecimal getFobAprice() {
        return (BigDecimal) getAttributeInternal(FOBAPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobAprice.
     * @param value value to set the FobAprice
     */
    public void setFobAprice(BigDecimal value) {
        setAttributeInternal(FOBAPRICE, value);
    }

    /**
     * Gets the attribute value for FobHigh, using the alias name FobHigh.
     * @return the value of FobHigh
     */
    public BigDecimal getFobHigh() {
        return (BigDecimal) getAttributeInternal(FOBHIGH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobHigh.
     * @param value value to set the FobHigh
     */
    public void setFobHigh(BigDecimal value) {
        setAttributeInternal(FOBHIGH, value);
    }

    /**
     * Gets the attribute value for FobLow, using the alias name FobLow.
     * @return the value of FobLow
     */
    public BigDecimal getFobLow() {
        return (BigDecimal) getAttributeInternal(FOBLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobLow.
     * @param value value to set the FobLow
     */
    public void setFobLow(BigDecimal value) {
        setAttributeInternal(FOBLOW, value);
    }

    /**
     * Gets the attribute value for FobVolume, using the alias name FobVolume.
     * @return the value of FobVolume
     */
    public BigDecimal getFobVolume() {
        return (BigDecimal) getAttributeInternal(FOBVOLUME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobVolume.
     * @param value value to set the FobVolume
     */
    public void setFobVolume(BigDecimal value) {
        setAttributeInternal(FOBVOLUME, value);
    }

    /**
     * Gets the attribute value for FobBrokerQty, using the alias name FobBrokerQty.
     * @return the value of FobBrokerQty
     */
    public BigDecimal getFobBrokerQty() {
        return (BigDecimal) getAttributeInternal(FOBBROKERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobBrokerQty.
     * @param value value to set the FobBrokerQty
     */
    public void setFobBrokerQty(BigDecimal value) {
        setAttributeInternal(FOBBROKERQTY, value);
    }

    /**
     * Gets the attribute value for FobBrokerCash, using the alias name FobBrokerCash.
     * @return the value of FobBrokerCash
     */
    public BigDecimal getFobBrokerCash() {
        return (BigDecimal) getAttributeInternal(FOBBROKERCASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobBrokerCash.
     * @param value value to set the FobBrokerCash
     */
    public void setFobBrokerCash(BigDecimal value) {
        setAttributeInternal(FOBBROKERCASH, value);
    }

    /**
     * Gets the attribute value for FobMarginAmt, using the alias name FobMarginAmt.
     * @return the value of FobMarginAmt
     */
    public BigDecimal getFobMarginAmt() {
        return (BigDecimal) getAttributeInternal(FOBMARGINAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobMarginAmt.
     * @param value value to set the FobMarginAmt
     */
    public void setFobMarginAmt(BigDecimal value) {
        setAttributeInternal(FOBMARGINAMT, value);
    }

    /**
     * Gets the attribute value for FobOstatus, using the alias name FobOstatus.
     * @return the value of FobOstatus
     */
    public String getFobOstatus() {
        return (String) getAttributeInternal(FOBOSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobOstatus.
     * @param value value to set the FobOstatus
     */
    public void setFobOstatus(String value) {
        setAttributeInternal(FOBOSTATUS, value);
    }

    /**
     * Gets the attribute value for FobEqty, using the alias name FobEqty.
     * @return the value of FobEqty
     */
    public BigDecimal getFobEqty() {
        return (BigDecimal) getAttributeInternal(FOBEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobEqty.
     * @param value value to set the FobEqty
     */
    public void setFobEqty(BigDecimal value) {
        setAttributeInternal(FOBEQTY, value);
    }

    /**
     * Gets the attribute value for FobEprice, using the alias name FobEprice.
     * @return the value of FobEprice
     */
    public BigDecimal getFobEprice() {
        return (BigDecimal) getAttributeInternal(FOBEPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobEprice.
     * @param value value to set the FobEprice
     */
    public void setFobEprice(BigDecimal value) {
        setAttributeInternal(FOBEPRICE, value);
    }

    /**
     * Gets the attribute value for WmsEnterUid, using the alias name WmsEnterUid.
     * @return the value of WmsEnterUid
     */
    public String getWmsEnterUid() {
        return (String) getAttributeInternal(WMSENTERUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsEnterUid.
     * @param value value to set the WmsEnterUid
     */
    public void setWmsEnterUid(String value) {
        setAttributeInternal(WMSENTERUID, value);
    }

    /**
     * Gets the attribute value for WmsEnterFpc, using the alias name WmsEnterFpc.
     * @return the value of WmsEnterFpc
     */
    public String getWmsEnterFpc() {
        return (String) getAttributeInternal(WMSENTERFPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsEnterFpc.
     * @param value value to set the WmsEnterFpc
     */
    public void setWmsEnterFpc(String value) {
        setAttributeInternal(WMSENTERFPC, value);
    }

    /**
     * Gets the attribute value for WmsEnterDate, using the alias name WmsEnterDate.
     * @return the value of WmsEnterDate
     */
    public Timestamp getWmsEnterDate() {
        return (Timestamp) getAttributeInternal(WMSENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsEnterDate.
     * @param value value to set the WmsEnterDate
     */
    public void setWmsEnterDate(Timestamp value) {
        setAttributeInternal(WMSENTERDATE, value);
    }

    /**
     * Gets the attribute value for WmsLastUpdateUid, using the alias name WmsLastUpdateUid.
     * @return the value of WmsLastUpdateUid
     */
    public String getWmsLastUpdateUid() {
        return (String) getAttributeInternal(WMSLASTUPDATEUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsLastUpdateUid.
     * @param value value to set the WmsLastUpdateUid
     */
    public void setWmsLastUpdateUid(String value) {
        setAttributeInternal(WMSLASTUPDATEUID, value);
    }

    /**
     * Gets the attribute value for WmsLastFpc, using the alias name WmsLastFpc.
     * @return the value of WmsLastFpc
     */
    public String getWmsLastFpc() {
        return (String) getAttributeInternal(WMSLASTFPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsLastFpc.
     * @param value value to set the WmsLastFpc
     */
    public void setWmsLastFpc(String value) {
        setAttributeInternal(WMSLASTFPC, value);
    }

    /**
     * Gets the attribute value for WmsLastUpdateDate, using the alias name WmsLastUpdateDate.
     * @return the value of WmsLastUpdateDate
     */
    public Timestamp getWmsLastUpdateDate() {
        return (Timestamp) getAttributeInternal(WMSLASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsLastUpdateDate.
     * @param value value to set the WmsLastUpdateDate
     */
    public void setWmsLastUpdateDate(Timestamp value) {
        setAttributeInternal(WMSLASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for WmsApproveUid, using the alias name WmsApproveUid.
     * @return the value of WmsApproveUid
     */
    public String getWmsApproveUid() {
        return (String) getAttributeInternal(WMSAPPROVEUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsApproveUid.
     * @param value value to set the WmsApproveUid
     */
    public void setWmsApproveUid(String value) {
        setAttributeInternal(WMSAPPROVEUID, value);
    }

    /**
     * Gets the attribute value for WmsApproveFpc, using the alias name WmsApproveFpc.
     * @return the value of WmsApproveFpc
     */
    public String getWmsApproveFpc() {
        return (String) getAttributeInternal(WMSAPPROVEFPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsApproveFpc.
     * @param value value to set the WmsApproveFpc
     */
    public void setWmsApproveFpc(String value) {
        setAttributeInternal(WMSAPPROVEFPC, value);
    }

    /**
     * Gets the attribute value for WmsApproveDate, using the alias name WmsApproveDate.
     * @return the value of WmsApproveDate
     */
    public Timestamp getWmsApproveDate() {
        return (Timestamp) getAttributeInternal(WMSAPPROVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsApproveDate.
     * @param value value to set the WmsApproveDate
     */
    public void setWmsApproveDate(Timestamp value) {
        setAttributeInternal(WMSAPPROVEDATE, value);
    }

    /**
     * @param fobNo key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long fobNo) {
        return new Key(new Object[] { fobNo });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.ciobera.fwms.trading.model.eo.FWMSOrderBookEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

