package com.ciobera.fwms.common.model.am.common;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 10 10:25:02 IST 2017
// ---------------------------------------------------------------------
public interface CommonAM extends ApplicationModule {
    Map clearWrongAttempt(String userId, String pc);

    Map logUserActivity(String userId, String pc, String screen, String type, String logMessage);

    Map logWrongAttempt(String userId, String pc);
}

