package com.ciobera.fwms.trading.model.am.common;

import java.util.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 09 14:26:40 IST 2017
// ---------------------------------------------------------------------
public interface TradingManagementAM extends ApplicationModule {
    void getFWMSHoldingRecordsForUserId(String userId);

    void processAsOfDateRecord(String userId, oracle.jbo.domain.Date asOfDate);
}

