package com.ciobera.fwms.order.model.am;

import com.ciobera.fwms.order.model.am.common.OrderManagementAM;
import com.ciobera.fwms.order.model.vo.readonly.FWMSDHoldingAllAssetDVOImpl;
import com.ciobera.fwms.order.model.vo.readonly.FWMSDHoldingAllAssetVOImpl;
import com.ciobera.fwms.order.model.vo.readonly.FWMSDHoldingAllCountryDVOImpl;
import com.ciobera.fwms.order.model.vo.readonly.FWMSDHoldingAllCountryVOImpl;
import com.ciobera.fwms.order.model.vo.readonly.FWMSDHoldingAllExchangeDVOImpl;
import com.ciobera.fwms.order.model.vo.readonly.FWMSDHoldingAllExchangeVOImpl;
import com.ciobera.fwms.order.model.vo.readonly.FWMSDHoldingAllVOImpl;


import java.util.Date;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 02 13:48:19 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderManagementAMImpl extends ApplicationModuleImpl implements OrderManagementAM {
    /**
     * This is the default constructor (do not remove).
     */
    public OrderManagementAMImpl() {
    }

    /**
     * This method is called to populate the Order Management data for the input date using the stored procedure .
     * @param userId
     * @param asOfDate
     */
    public void processAsOfDateRecord(String userId, Date asOfDate) {
        //TODO call Stored Procedure to fill the data in the table forthe selected user and asof date
    }

    public void getFWMSHoldingRecordsForUserId(String userId) {
        if (userId != null) {
            FWMSDHoldingAllVOImpl holdingAllVOImpl = getFWMSDHoldingAll();
            if (holdingAllVOImpl != null) {
                holdingAllVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllVOImpl.executeQuery();
            }

            FWMSDHoldingAllAssetVOImpl holdingAllAssetVOImpl = getFWMSDHoldingAllAsset();
            if (holdingAllAssetVOImpl != null) {
                holdingAllAssetVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllAssetVOImpl.executeQuery();
            }

            FWMSDHoldingAllCountryVOImpl holdingAllCountryVOImpl = getFWMSDHoldingAllCountry();
            if (holdingAllCountryVOImpl != null) {
                holdingAllCountryVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllCountryVOImpl.executeQuery();
            }

            FWMSDHoldingAllExchangeVOImpl holdingAllExchangeVOImpl = getFWMSDHoldingAllExchange();
            if (holdingAllExchangeVOImpl != null) {
                holdingAllExchangeVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllExchangeVOImpl.executeQuery();
            }
            
            FWMSDHoldingAllExchangeDVOImpl holdingAllExchangeDVOImpl = getFWMSDHoldingAllExchangeD();
            if(holdingAllExchangeDVOImpl != null){
                holdingAllExchangeDVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllExchangeDVOImpl.executeQuery();
            }
            
            FWMSDHoldingAllCountryDVOImpl holdingAllCountryDVOImpl = getFWMSDHoldingAllCountryD();
            if(holdingAllCountryDVOImpl != null){
                holdingAllCountryDVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllCountryDVOImpl.executeQuery();
            }
            
            FWMSDHoldingAllAssetDVOImpl holdingAllAssetDVOImpl = getFWMSDHoldingAllAssetD();
            if(holdingAllAssetDVOImpl != null){
                holdingAllAssetDVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllAssetDVOImpl.executeQuery();
            }
            ViewObjectImpl holdingAllAssetSVOImpl = getFWMSDHoldingAllAssetSVO();
            if(holdingAllAssetDVOImpl != null){
                holdingAllAssetDVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllAssetDVOImpl.executeQuery();
            }
            ViewObjectImpl holdingSelectedVOImpl = getFWMSDHoldingSelectedVO();
            if(holdingSelectedVOImpl != null){
                holdingSelectedVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingSelectedVOImpl.executeQuery();
            }
            ViewObjectImpl holdingAllExchangeSVOImpl = getFWMSDHoldingAllExchangeSVO();
            if(holdingAllExchangeSVOImpl != null){
                holdingAllExchangeSVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllExchangeSVOImpl.executeQuery();
            }
            ViewObjectImpl holdingAllCountrySVOImpl = getFWMSDHoldingAllCountrySVO();
            if(holdingAllCountrySVOImpl != null){
                holdingAllCountrySVOImpl.setNamedWhereClauseParam("loggedInUserId", userId);
                holdingAllCountrySVOImpl.executeQuery();
            }
            
        }
    }

    /**
     * Container's getter for FWMSDHoldingAllVO1.
     * @return FWMSDHoldingAllVO1
     */
    public FWMSDHoldingAllVOImpl getFWMSDHoldingAll() {
        return (FWMSDHoldingAllVOImpl) findViewObject("FWMSDHoldingAll");
    }

    /**
     * Container's getter for FWMSDHoldingAllAssetVO1.
     * @return FWMSDHoldingAllAssetVO1
     */
    public FWMSDHoldingAllAssetVOImpl getFWMSDHoldingAllAsset() {
        return (FWMSDHoldingAllAssetVOImpl) findViewObject("FWMSDHoldingAllAsset");
    }

    /**
     * Container's getter for FWMSDHoldingAllAssetDVO1.
     * @return FWMSDHoldingAllAssetDVO1
     */
    public FWMSDHoldingAllAssetDVOImpl getFWMSDHoldingAllAssetD() {
        return (FWMSDHoldingAllAssetDVOImpl) findViewObject("FWMSDHoldingAllAssetD");
    }

    /**
     * Container's getter for FWMSDHoldingAllAssetVOToFWMSDHoldingAllAssetDVO1.
     * @return FWMSDHoldingAllAssetVOToFWMSDHoldingAllAssetDVO1
     */
    public ViewLinkImpl getFWMSDHoldingAllAssetVOToFWMSDHoldingAllAssetDVO() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllAssetVOToFWMSDHoldingAllAssetDVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllCountryVO1.
     * @return FWMSDHoldingAllCountryVO1
     */
    public FWMSDHoldingAllCountryVOImpl getFWMSDHoldingAllCountry() {
        return (FWMSDHoldingAllCountryVOImpl) findViewObject("FWMSDHoldingAllCountry");
    }

    /**
     * Container's getter for FWMSDHoldingAllCountryDVO1.
     * @return FWMSDHoldingAllCountryDVO1
     */
    public FWMSDHoldingAllCountryDVOImpl getFWMSDHoldingAllCountryD() {
        return (FWMSDHoldingAllCountryDVOImpl) findViewObject("FWMSDHoldingAllCountryD");
    }

    /**
     * Container's getter for FWMSHoldingAllCountryVOToFWMSHoldingAllCountryDVO1.
     * @return FWMSHoldingAllCountryVOToFWMSHoldingAllCountryDVO1
     */
    public ViewLinkImpl getFWMSHoldingAllCountryVOToFWMSHoldingAllCountryDVO() {
        return (ViewLinkImpl) findViewLink("FWMSHoldingAllCountryVOToFWMSHoldingAllCountryDVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllExchangeVO1.
     * @return FWMSDHoldingAllExchangeVO1
     */
    public FWMSDHoldingAllExchangeVOImpl getFWMSDHoldingAllExchange() {
        return (FWMSDHoldingAllExchangeVOImpl) findViewObject("FWMSDHoldingAllExchange");
    }

    /**
     * Container's getter for FWMSDHoldingAllExchangeDVO1.
     * @return FWMSDHoldingAllExchangeDVO1
     */
    public FWMSDHoldingAllExchangeDVOImpl getFWMSDHoldingAllExchangeD() {
        return (FWMSDHoldingAllExchangeDVOImpl) findViewObject("FWMSDHoldingAllExchangeD");
    }

    /**
     * Container's getter for FWMSDHoldingAllExchangeVOToFWMSDHoldingAllExchangeDVO1.
     * @return FWMSDHoldingAllExchangeVOToFWMSDHoldingAllExchangeDVO1
     */
    public ViewLinkImpl getFWMSDHoldingAllExchangeVOToFWMSDHoldingAllExchangeDVO() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllExchangeVOToFWMSDHoldingAllExchangeDVO");
    }

    /**
     * Container's getter for FWMSDHoldingSelectedVO1.
     * @return FWMSDHoldingSelectedVO1
     */
    public ViewObjectImpl getFWMSDHoldingSelectedVO() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingSelectedVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllVOToFWMSDHoldingSelectedSVO1.
     * @return FWMSDHoldingAllVOToFWMSDHoldingSelectedSVO1
     */
    public ViewLinkImpl getFWMSDHoldingAllVOToFWMSDHoldingSelectedSVO1() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllVOToFWMSDHoldingSelectedSVO1");
    }

    /**
     * Container's getter for FWMSDHoldingAllCountrySVO1.
     * @return FWMSDHoldingAllCountrySVO1
     */
    public ViewObjectImpl getFWMSDHoldingAllCountrySVO() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllCountrySVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllVOToFWMSDHoldingAllCountrySVO1.
     * @return FWMSDHoldingAllVOToFWMSDHoldingAllCountrySVO1
     */
    public ViewLinkImpl getFWMSDHoldingAllVOToFWMSDHoldingAllCountrySVO1() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllVOToFWMSDHoldingAllCountrySVO1");
    }

    /**
     * Container's getter for FWMSDHoldingAllExchangeSVO2.
     * @return FWMSDHoldingAllExchangeSVO2
     */
    public ViewObjectImpl getFWMSDHoldingAllExchangeSVO() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllExchangeSVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllVOToFWMSDHoldingAllExchangeSVO2.
     * @return FWMSDHoldingAllVOToFWMSDHoldingAllExchangeSVO2
     */
    public ViewLinkImpl getFWMSDHoldingAllVOToFWMSDHoldingAllExchangeSVO2() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllVOToFWMSDHoldingAllExchangeSVO2");
    }

    /**
     * Container's getter for FWMSDHoldingAllAssetSVO1.
     * @return FWMSDHoldingAllAssetSVO1
     */
    public ViewObjectImpl getFWMSDHoldingAllAssetSVO() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllAssetSVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllVOToFWMSDHoldingAllAssetSVO1.
     * @return FWMSDHoldingAllVOToFWMSDHoldingAllAssetSVO1
     */
    public ViewLinkImpl getFWMSDHoldingAllVOToFWMSDHoldingAllAssetSVO1() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllVOToFWMSDHoldingAllAssetSVO1");
    }

    /**
     * Container's getter for FWMSDHoldingSelectedVO1.
     * @return FWMSDHoldingSelectedVO1
     */
    public ViewObjectImpl getFWMSDHoldingSelected() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingSelected");
    }

    /**
     * Container's getter for FWMSDHoldingAllVOToFWMSDHoldingAllExchangeSVO1.
     * @return FWMSDHoldingAllVOToFWMSDHoldingAllExchangeSVO1
     */
    public ViewLinkImpl getFWMSDHoldingAllVOToFWMSDHoldingAllExchangeSVO1() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllVOToFWMSDHoldingAllExchangeSVO1");
    }

    /**
     * Container's getter for FWMSDHoldingAllAssetSVO1.
     * @return FWMSDHoldingAllAssetSVO1
     */
    public ViewObjectImpl getFWMSDHoldingAllAssetS() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllAssetS");
    }

    /**
     * Container's getter for FWMSDHoldingAllCountrySVO1.
     * @return FWMSDHoldingAllCountrySVO1
     */
    public ViewObjectImpl getFWMSDHoldingAllCountryS() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllCountryS");
    }

    /**
     * Container's getter for FWMSDHoldingAllExchangeSVO1.
     * @return FWMSDHoldingAllExchangeSVO1
     */
    public ViewObjectImpl getFWMSDHoldingAllExchangeS() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllExchangeS");
    }
}

