package com.ciobera.fwms.order.model.am;

import com.ciobera.fwms.order.model.am.common.OrderManagementAM;
import com.ciobera.fwms.order.model.vo.readonly.FWMSDHoldingAllVOImpl;

import java.util.Date;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 02 13:48:19 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderManagementAMImpl extends ApplicationModuleImpl implements OrderManagementAM {
    /**
     * This is the default constructor (do not remove).
     */
    public OrderManagementAMImpl() {
    }
    
    /**
     * This method is called to populate the Order Management data for the input date using the stored procedure .
     * @param userId
     * @param asOfDate
     */
    public void processAsOfDateRecord(String userId, Date asOfDate) {
        //TODO call Stored Procedure to fill the data in the table forthe selected user and asof date 
    }


    /**
     * Container's getter for FWMSHoldingAllVO1.
     * @return FWMSHoldingAllVO1
     */
    public FWMSDHoldingAllVOImpl getFWMSHoldingAllVO() {
        return (FWMSDHoldingAllVOImpl) findViewObject("FWMSHoldingAllVO");
    }

    /**
     * Container's getter for FWMSHoldingAllCountryVO1.
     * @return FWMSHoldingAllCountryVO1
     */
    public ViewObjectImpl getFWMSHoldingAllCountryVO() {
        return (ViewObjectImpl) findViewObject("FWMSHoldingAllCountryVO");
    }

    /**
     * Container's getter for FWMSHoldingAllCountryDVO1.
     * @return FWMSHoldingAllCountryDVO1
     */
    public ViewObjectImpl getFWMSHoldingAllCountryDVO() {
        return (ViewObjectImpl) findViewObject("FWMSHoldingAllCountryDVO");
    }

    /**
     * Container's getter for FWMSHoldingAllCountryVOToFWMSHoldingAllCountryDVO1.
     * @return FWMSHoldingAllCountryVOToFWMSHoldingAllCountryDVO1
     */
    public ViewLinkImpl getFWMSHoldingAllCountryVOToFWMSHoldingAllCountryDVO1() {
        return (ViewLinkImpl) findViewLink("FWMSHoldingAllCountryVOToFWMSHoldingAllCountryDVO1");
    }

    /**
     * Container's getter for FWMSHoldingAllCountryDVO1.
     * @return FWMSHoldingAllCountryDVO1
     */
    public ViewObjectImpl getFWMSHoldingAllCountryDVO1() {
        return (ViewObjectImpl) findViewObject("FWMSHoldingAllCountryDVO1");
    }

    /**
     * Container's getter for FWMSHoldingAllAssetVO1.
     * @return FWMSHoldingAllAssetVO1
     */
    public ViewObjectImpl getFWMSHoldingAllAssetVO() {
        return (ViewObjectImpl) findViewObject("FWMSHoldingAllAssetVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllAssetDVO1.
     * @return FWMSDHoldingAllAssetDVO1
     */
    public ViewObjectImpl getFWMSDHoldingAllAssetDVO() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllAssetDVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllAssetVOToFWMSDHoldingAllAssetDVO1.
     * @return FWMSDHoldingAllAssetVOToFWMSDHoldingAllAssetDVO1
     */
    public ViewLinkImpl getFWMSDHoldingAllAssetVOToFWMSDHoldingAllAssetDVO1() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllAssetVOToFWMSDHoldingAllAssetDVO1");
    }

    /**
     * Container's getter for FWMSDHoldingAllExchangeVO1.
     * @return FWMSDHoldingAllExchangeVO1
     */
    public ViewObjectImpl getFWMSDHoldingAllExchangeVO() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllExchangeVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllExchangeDVO1.
     * @return FWMSDHoldingAllExchangeDVO1
     */
    public ViewObjectImpl getFWMSDHoldingAllExchangeDVO() {
        return (ViewObjectImpl) findViewObject("FWMSDHoldingAllExchangeDVO");
    }

    /**
     * Container's getter for FWMSDHoldingAllExchangeVOToFWMSDHoldingAllExchangeDVO1.
     * @return FWMSDHoldingAllExchangeVOToFWMSDHoldingAllExchangeDVO1
     */
    public ViewLinkImpl getFWMSDHoldingAllExchangeVOToFWMSDHoldingAllExchangeDVO1() {
        return (ViewLinkImpl) findViewLink("FWMSDHoldingAllExchangeVOToFWMSDHoldingAllExchangeDVO1");
    }
}

