package com.ciobera.fwms.trading.model.vo.readonly.common;

import java.util.Map;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 11 00:45:47 IST 2017
// ---------------------------------------------------------------------
public interface FWMSDHoldingSelectedVO extends ViewObject {
    Map getCount();

    Map getSum();
}

