package com.ciobera.fwms.common.model.vo.readonly;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 10 10:20:17 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSUsersVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WmsUserSno,
        WmsCreateDate,
        WmsEmployeeNo,
        WmsName,
        WmsUserId,
        WmsUserPassword,
        WmsGroup,
        WmsGroupPrevilige,
        WmsPreviligeFlag,
        WmsExpiryDays,
        WmsLastLogin,
        WmsLastPasswordChange,
        WmsBlock,
        WmsStatus,
        WmsStatusCdate,
        WmsRemarks,
        WmsEnterUid,
        WmsEnterFpc,
        WmsEnterDate,
        WmsLastUpdateUid,
        WmsLastFpc,
        WmsLastUpdateDate,
        WmsApproveUid,
        WmsApproveFpc,
        WmsApproveDate,
        WmsComments,
        WmsEmail,
        WmsCompId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WMSUSERSNO = AttributesEnum.WmsUserSno.index();
    public static final int WMSCREATEDATE = AttributesEnum.WmsCreateDate.index();
    public static final int WMSEMPLOYEENO = AttributesEnum.WmsEmployeeNo.index();
    public static final int WMSNAME = AttributesEnum.WmsName.index();
    public static final int WMSUSERID = AttributesEnum.WmsUserId.index();
    public static final int WMSUSERPASSWORD = AttributesEnum.WmsUserPassword.index();
    public static final int WMSGROUP = AttributesEnum.WmsGroup.index();
    public static final int WMSGROUPPREVILIGE = AttributesEnum.WmsGroupPrevilige.index();
    public static final int WMSPREVILIGEFLAG = AttributesEnum.WmsPreviligeFlag.index();
    public static final int WMSEXPIRYDAYS = AttributesEnum.WmsExpiryDays.index();
    public static final int WMSLASTLOGIN = AttributesEnum.WmsLastLogin.index();
    public static final int WMSLASTPASSWORDCHANGE = AttributesEnum.WmsLastPasswordChange.index();
    public static final int WMSBLOCK = AttributesEnum.WmsBlock.index();
    public static final int WMSSTATUS = AttributesEnum.WmsStatus.index();
    public static final int WMSSTATUSCDATE = AttributesEnum.WmsStatusCdate.index();
    public static final int WMSREMARKS = AttributesEnum.WmsRemarks.index();
    public static final int WMSENTERUID = AttributesEnum.WmsEnterUid.index();
    public static final int WMSENTERFPC = AttributesEnum.WmsEnterFpc.index();
    public static final int WMSENTERDATE = AttributesEnum.WmsEnterDate.index();
    public static final int WMSLASTUPDATEUID = AttributesEnum.WmsLastUpdateUid.index();
    public static final int WMSLASTFPC = AttributesEnum.WmsLastFpc.index();
    public static final int WMSLASTUPDATEDATE = AttributesEnum.WmsLastUpdateDate.index();
    public static final int WMSAPPROVEUID = AttributesEnum.WmsApproveUid.index();
    public static final int WMSAPPROVEFPC = AttributesEnum.WmsApproveFpc.index();
    public static final int WMSAPPROVEDATE = AttributesEnum.WmsApproveDate.index();
    public static final int WMSCOMMENTS = AttributesEnum.WmsComments.index();
    public static final int WMSEMAIL = AttributesEnum.WmsEmail.index();
    public static final int WMSCOMPID = AttributesEnum.WmsCompId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSUsersVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WmsUserSno.
     * @return the WmsUserSno
     */
    public Long getWmsUserSno() {
        return (Long) getAttributeInternal(WMSUSERSNO);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsCreateDate.
     * @return the WmsCreateDate
     */
    public Date getWmsCreateDate() {
        return (Date) getAttributeInternal(WMSCREATEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsEmployeeNo.
     * @return the WmsEmployeeNo
     */
    public Long getWmsEmployeeNo() {
        return (Long) getAttributeInternal(WMSEMPLOYEENO);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsName.
     * @return the WmsName
     */
    public String getWmsName() {
        return (String) getAttributeInternal(WMSNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsUserId.
     * @return the WmsUserId
     */
    public String getWmsUserId() {
        return (String) getAttributeInternal(WMSUSERID);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsUserPassword.
     * @return the WmsUserPassword
     */
    public String getWmsUserPassword() {
        return (String) getAttributeInternal(WMSUSERPASSWORD);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsGroup.
     * @return the WmsGroup
     */
    public Integer getWmsGroup() {
        return (Integer) getAttributeInternal(WMSGROUP);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsGroupPrevilige.
     * @return the WmsGroupPrevilige
     */
    public Integer getWmsGroupPrevilige() {
        return (Integer) getAttributeInternal(WMSGROUPPREVILIGE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsPreviligeFlag.
     * @return the WmsPreviligeFlag
     */
    public Integer getWmsPreviligeFlag() {
        return (Integer) getAttributeInternal(WMSPREVILIGEFLAG);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsExpiryDays.
     * @return the WmsExpiryDays
     */
    public Integer getWmsExpiryDays() {
        return (Integer) getAttributeInternal(WMSEXPIRYDAYS);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsLastLogin.
     * @return the WmsLastLogin
     */
    public Date getWmsLastLogin() {
        return (Date) getAttributeInternal(WMSLASTLOGIN);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsLastPasswordChange.
     * @return the WmsLastPasswordChange
     */
    public Date getWmsLastPasswordChange() {
        return (Date) getAttributeInternal(WMSLASTPASSWORDCHANGE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsBlock.
     * @return the WmsBlock
     */
    public String getWmsBlock() {
        return (String) getAttributeInternal(WMSBLOCK);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsStatus.
     * @return the WmsStatus
     */
    public String getWmsStatus() {
        return (String) getAttributeInternal(WMSSTATUS);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsStatusCdate.
     * @return the WmsStatusCdate
     */
    public Date getWmsStatusCdate() {
        return (Date) getAttributeInternal(WMSSTATUSCDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsRemarks.
     * @return the WmsRemarks
     */
    public String getWmsRemarks() {
        return (String) getAttributeInternal(WMSREMARKS);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsEnterUid.
     * @return the WmsEnterUid
     */
    public String getWmsEnterUid() {
        return (String) getAttributeInternal(WMSENTERUID);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsEnterFpc.
     * @return the WmsEnterFpc
     */
    public String getWmsEnterFpc() {
        return (String) getAttributeInternal(WMSENTERFPC);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsEnterDate.
     * @return the WmsEnterDate
     */
    public Date getWmsEnterDate() {
        return (Date) getAttributeInternal(WMSENTERDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsLastUpdateUid.
     * @return the WmsLastUpdateUid
     */
    public String getWmsLastUpdateUid() {
        return (String) getAttributeInternal(WMSLASTUPDATEUID);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsLastFpc.
     * @return the WmsLastFpc
     */
    public String getWmsLastFpc() {
        return (String) getAttributeInternal(WMSLASTFPC);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsLastUpdateDate.
     * @return the WmsLastUpdateDate
     */
    public Date getWmsLastUpdateDate() {
        return (Date) getAttributeInternal(WMSLASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsApproveUid.
     * @return the WmsApproveUid
     */
    public String getWmsApproveUid() {
        return (String) getAttributeInternal(WMSAPPROVEUID);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsApproveFpc.
     * @return the WmsApproveFpc
     */
    public String getWmsApproveFpc() {
        return (String) getAttributeInternal(WMSAPPROVEFPC);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsApproveDate.
     * @return the WmsApproveDate
     */
    public Date getWmsApproveDate() {
        return (Date) getAttributeInternal(WMSAPPROVEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsComments.
     * @return the WmsComments
     */
    public String getWmsComments() {
        return (String) getAttributeInternal(WMSCOMMENTS);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsEmail.
     * @return the WmsEmail
     */
    public String getWmsEmail() {
        return (String) getAttributeInternal(WMSEMAIL);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsCompId.
     * @return the WmsCompId
     */
    public Integer getWmsCompId() {
        return (Integer) getAttributeInternal(WMSCOMPID);
    }
}

