package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 14:44:39 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSSectorVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WmsSectorId,
        WmsSectorDesc;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int WMSSECTORID = AttributesEnum.WmsSectorId.index();
    public static final int WMSSECTORDESC = AttributesEnum.WmsSectorDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSSectorVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WmsSectorId.
     * @return the WmsSectorId
     */
    public Integer getWmsSectorId() {
        return (Integer) getAttributeInternal(WMSSECTORID);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsSectorDesc.
     * @return the WmsSectorDesc
     */
    public String getWmsSectorDesc() {
        return (String) getAttributeInternal(WMSSECTORDESC);
    }
}

