package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 14:44:39 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSSectorVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSSectorVOImpl() {
    }

    /**
     * Returns the variable value for pSector.
     * @return variable value for pSector
     */
    public String getpSector() {
        return (String) ensureVariableManager().getVariableValue("pSector");
    }

    /**
     * Sets <code>value</code> for variable pSector.
     * @param value value to bind as pSector
     */
    public void setpSector(String value) {
        ensureVariableManager().setVariableValue("pSector", value);
    }
}

