package com.ciobera.fwms.common.model.vo.readonly;

import java.math.BigInteger;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 14:42:42 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSCountryVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WmsCountryId,
        WmsCountryDesc;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int WMSCOUNTRYID = AttributesEnum.WmsCountryId.index();
    public static final int WMSCOUNTRYDESC = AttributesEnum.WmsCountryDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSCountryVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WmsCountryId.
     * @return the WmsCountryId
     */
    public BigInteger getWmsCountryId() {
        return (BigInteger) getAttributeInternal(WMSCOUNTRYID);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsCountryDesc.
     * @return the WmsCountryDesc
     */
    public String getWmsCountryDesc() {
        return (String) getAttributeInternal(WMSCOUNTRYDESC);
    }
}

