package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 09:58:43 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSMainMenuVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSMainMenuVOImpl() {
    }

    /**
     * Returns the variable value for pUserId.
     * @return variable value for pUserId
     */
    public String getpUserId() {
        return (String) ensureVariableManager().getVariableValue("pUserId");
    }

    /**
     * Sets <code>value</code> for variable pUserId.
     * @param value value to bind as pUserId
     */
    public void setpUserId(String value) {
        ensureVariableManager().setVariableValue("pUserId", value);
    }

    /**
     * Returns the variable value for pSNo.
     * @return variable value for pSNo
     */
    public Integer getpSNo() {
        return (Integer) ensureVariableManager().getVariableValue("pSNo");
    }

    /**
     * Sets <code>value</code> for variable pSNo.
     * @param value value to bind as pSNo
     */
    public void setpSNo(Integer value) {
        ensureVariableManager().setVariableValue("pSNo", value);
    }
}

