package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 14:45:12 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSStockExchangeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSStockExchangeVOImpl() {
    }

    /**
     * Returns the variable value for pStockExchange.
     * @return variable value for pStockExchange
     */
    public String getpStockExchange() {
        return (String) ensureVariableManager().getVariableValue("pStockExchange");
    }

    /**
     * Sets <code>value</code> for variable pStockExchange.
     * @param value value to bind as pStockExchange
     */
    public void setpStockExchange(String value) {
        ensureVariableManager().setVariableValue("pStockExchange", value);
    }
}

