package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 14:43:47 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSCurrencyVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WmsCurrencyId,
        WmsCurrencyDesc,
        WmsShortDesc;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int WMSCURRENCYID = AttributesEnum.WmsCurrencyId.index();
    public static final int WMSCURRENCYDESC = AttributesEnum.WmsCurrencyDesc.index();
    public static final int WMSSHORTDESC = AttributesEnum.WmsShortDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSCurrencyVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WmsCurrencyId.
     * @return the WmsCurrencyId
     */
    public Integer getWmsCurrencyId() {
        return (Integer) getAttributeInternal(WMSCURRENCYID);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsCurrencyDesc.
     * @return the WmsCurrencyDesc
     */
    public String getWmsCurrencyDesc() {
        return (String) getAttributeInternal(WMSCURRENCYDESC);
    }

    /**
     * Gets the attribute value for the calculated attribute WmsShortDesc.
     * @return the WmsShortDesc
     */
    public String getWmsShortDesc() {
        return (String) getAttributeInternal(WMSSHORTDESC);
    }
}

