package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 09:58:29 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSMainMenuVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WmmUserid,
        WmmMenu,
        WmmPnode,
        WmmCnode,
        WmmDesc,
        WmmFile,
        WmmView,
        WmmInsert,
        WmmUpdate,
        WmmDelete,
        WmmMakerChecker,
        WmmSno,
        WmmCnodeFWMSMainMenuVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WMMUSERID = AttributesEnum.WmmUserid.index();
    public static final int WMMMENU = AttributesEnum.WmmMenu.index();
    public static final int WMMPNODE = AttributesEnum.WmmPnode.index();
    public static final int WMMCNODE = AttributesEnum.WmmCnode.index();
    public static final int WMMDESC = AttributesEnum.WmmDesc.index();
    public static final int WMMFILE = AttributesEnum.WmmFile.index();
    public static final int WMMVIEW = AttributesEnum.WmmView.index();
    public static final int WMMINSERT = AttributesEnum.WmmInsert.index();
    public static final int WMMUPDATE = AttributesEnum.WmmUpdate.index();
    public static final int WMMDELETE = AttributesEnum.WmmDelete.index();
    public static final int WMMMAKERCHECKER = AttributesEnum.WmmMakerChecker.index();
    public static final int WMMSNO = AttributesEnum.WmmSno.index();
    public static final int WMMCNODEFWMSMAINMENUVO = AttributesEnum.WmmCnodeFWMSMainMenuVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSMainMenuVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WmmUserid.
     * @return the WmmUserid
     */
    public String getWmmUserid() {
        return (String) getAttributeInternal(WMMUSERID);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmMenu.
     * @return the WmmMenu
     */
    public Integer getWmmMenu() {
        return (Integer) getAttributeInternal(WMMMENU);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmPnode.
     * @return the WmmPnode
     */
    public Integer getWmmPnode() {
        return (Integer) getAttributeInternal(WMMPNODE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmCnode.
     * @return the WmmCnode
     */
    public Integer getWmmCnode() {
        return (Integer) getAttributeInternal(WMMCNODE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmDesc.
     * @return the WmmDesc
     */
    public String getWmmDesc() {
        return (String) getAttributeInternal(WMMDESC);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmFile.
     * @return the WmmFile
     */
    public String getWmmFile() {
        return (String) getAttributeInternal(WMMFILE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmView.
     * @return the WmmView
     */
    public String getWmmView() {
        return (String) getAttributeInternal(WMMVIEW);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmInsert.
     * @return the WmmInsert
     */
    public String getWmmInsert() {
        return (String) getAttributeInternal(WMMINSERT);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmUpdate.
     * @return the WmmUpdate
     */
    public String getWmmUpdate() {
        return (String) getAttributeInternal(WMMUPDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmDelete.
     * @return the WmmDelete
     */
    public String getWmmDelete() {
        return (String) getAttributeInternal(WMMDELETE);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmMakerChecker.
     * @return the WmmMakerChecker
     */
    public String getWmmMakerChecker() {
        return (String) getAttributeInternal(WMMMAKERCHECKER);
    }

    /**
     * Gets the attribute value for the calculated attribute WmmSno.
     * @return the WmmSno
     */
    public Integer getWmmSno() {
        return (Integer) getAttributeInternal(WMMSNO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WmmCnodeFWMSMainMenuVO.
     */
    public RowIterator getWmmCnodeFWMSMainMenuVO() {
        return (RowIterator) getAttributeInternal(WMMCNODEFWMSMAINMENUVO);
    }


}

