package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 14:45:12 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSStockExchangeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSStockExchangeVOImpl() {
    }
}

