package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 14:42:02 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSAssetVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSAssetVOImpl() {
    }

    /**
     * Returns the variable value for pAsset.
     * @return variable value for pAsset
     */
    public String getpAsset() {
        return (String) ensureVariableManager().getVariableValue("pAsset");
    }

    /**
     * Sets <code>value</code> for variable pAsset.
     * @param value value to bind as pAsset
     */
    public void setpAsset(String value) {
        ensureVariableManager().setVariableValue("pAsset", value);
    }
}

