package com.ciobera.fwms.common.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 10 10:20:18 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSUsersVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSUsersVOImpl() {
    }

    /**
     * Returns the variable value for pUserId.
     * @return variable value for pUserId
     */
    public String getpUserId() {
        return (String) ensureVariableManager().getVariableValue("pUserId");
    }

    /**
     * Sets <code>value</code> for variable pUserId.
     * @param value value to bind as pUserId
     */
    public void setpUserId(String value) {
        ensureVariableManager().setVariableValue("pUserId", value);
    }

    /**
     * Returns the variable value for pUserPassword.
     * @return variable value for pUserPassword
     */
    public String getpUserPassword() {
        return (String) ensureVariableManager().getVariableValue("pUserPassword");
    }

    /**
     * Sets <code>value</code> for variable pUserPassword.
     * @param value value to bind as pUserPassword
     */
    public void setpUserPassword(String value) {
        ensureVariableManager().setVariableValue("pUserPassword", value);
    }
}

