package com.ciobera.fwms.order.model.am.common;

import java.util.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 02 13:53:18 IST 2017
// ---------------------------------------------------------------------
public interface OrderManagementAM extends ApplicationModule {
    void processAsOfDateRecord(String userId, Date asOfDate);
}

