package com.ciobera.fwms.root.model.am;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 11 10:18:49 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSRootAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSRootAMImpl() {
    }

    /**
     * Container's getter for CommonAM.
     * @return CommonAM
     */
    public ApplicationModuleImpl getCommonAM() {
        return (ApplicationModuleImpl) findApplicationModule("CommonAM");
    }
}

