package com.ciobera.fwms.order.model.vo.readonly;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 02 14:10:45 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSDHoldingAllVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FhaUserid,
        FhaFund,
        FhaFname,
        FhaCashB,
        FhaMvB,
        FhaNavB,
        FhaNavNavD,
        FhaNavNavDp,
        FhaNavNavW,
        FhaNavNavWp,
        FhaNavNavM,
        FhaNavNavMp,
        FhaNavNavY,
        FhaNavNavYp,
        FhaNavNavYtd,
        FhaNavNavYtdp;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return FWMSDHoldingAllVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return FWMSDHoldingAllVORowImpl.AttributesEnum.firstIndex() + FWMSDHoldingAllVORowImpl.AttributesEnum
                                                                                                  .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = FWMSDHoldingAllVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FHAUSERID = AttributesEnum.FhaUserid.index();
    public static final int FHAFUND = AttributesEnum.FhaFund.index();
    public static final int FHAFNAME = AttributesEnum.FhaFname.index();
    public static final int FHACASHB = AttributesEnum.FhaCashB.index();
    public static final int FHAMVB = AttributesEnum.FhaMvB.index();
    public static final int FHANAVB = AttributesEnum.FhaNavB.index();
    public static final int FHANAVNAVD = AttributesEnum.FhaNavNavD.index();
    public static final int FHANAVNAVDP = AttributesEnum.FhaNavNavDp.index();
    public static final int FHANAVNAVW = AttributesEnum.FhaNavNavW.index();
    public static final int FHANAVNAVWP = AttributesEnum.FhaNavNavWp.index();
    public static final int FHANAVNAVM = AttributesEnum.FhaNavNavM.index();
    public static final int FHANAVNAVMP = AttributesEnum.FhaNavNavMp.index();
    public static final int FHANAVNAVY = AttributesEnum.FhaNavNavY.index();
    public static final int FHANAVNAVYP = AttributesEnum.FhaNavNavYp.index();
    public static final int FHANAVNAVYTD = AttributesEnum.FhaNavNavYtd.index();
    public static final int FHANAVNAVYTDP = AttributesEnum.FhaNavNavYtdp.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSDHoldingAllVORowImpl() {
    }
}

