package com.ciobera.fwms.order.model.vo.readonly;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 19:38:37 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSDHoldingAllExchangeDVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FhaFund,
        FhaFname,
        FhaExchange,
        FhaEname,
        FhaMvB;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FHAFUND = AttributesEnum.FhaFund.index();
    public static final int FHAFNAME = AttributesEnum.FhaFname.index();
    public static final int FHAEXCHANGE = AttributesEnum.FhaExchange.index();
    public static final int FHAENAME = AttributesEnum.FhaEname.index();
    public static final int FHAMVB = AttributesEnum.FhaMvB.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSDHoldingAllExchangeDVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute FhaFund.
     * @return the FhaFund
     */
    public Long getFhaFund() {
        return (Long) getAttributeInternal(FHAFUND);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaFname.
     * @return the FhaFname
     */
    public String getFhaFname() {
        return (String) getAttributeInternal(FHAFNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaExchange.
     * @return the FhaExchange
     */
    public Long getFhaExchange() {
        return (Long) getAttributeInternal(FHAEXCHANGE);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaEname.
     * @return the FhaEname
     */
    public String getFhaEname() {
        return (String) getAttributeInternal(FHAENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaMvB.
     * @return the FhaMvB
     */
    public BigDecimal getFhaMvB() {
        return (BigDecimal) getAttributeInternal(FHAMVB);
    }
}

