package com.ciobera.fwms.order.model.vo.readonly;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 19:37:53 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSDHoldingAllCountryDVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FhaCname,
        FhaMvB,
        FhaCountry,
        FhaFname,
        FhaFund;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FHACNAME = AttributesEnum.FhaCname.index();
    public static final int FHAMVB = AttributesEnum.FhaMvB.index();
    public static final int FHACOUNTRY = AttributesEnum.FhaCountry.index();
    public static final int FHAFNAME = AttributesEnum.FhaFname.index();
    public static final int FHAFUND = AttributesEnum.FhaFund.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSDHoldingAllCountryDVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute FhaCname.
     * @return the FhaCname
     */
    public String getFhaCname() {
        return (String) getAttributeInternal(FHACNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaMvB.
     * @return the FhaMvB
     */
    public BigDecimal getFhaMvB() {
        return (BigDecimal) getAttributeInternal(FHAMVB);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaCountry.
     * @return the FhaCountry
     */
    public Long getFhaCountry() {
        return (Long) getAttributeInternal(FHACOUNTRY);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaFname.
     * @return the FhaFname
     */
    public String getFhaFname() {
        return (String) getAttributeInternal(FHAFNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaFund.
     * @return the FhaFund
     */
    public Long getFhaFund() {
        return (Long) getAttributeInternal(FHAFUND);
    }
}

