package com.ciobera.fwms.order.model.vo.readonly;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 19:38:52 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSDHoldingAllExchangeVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FhaEname,
        FhaMvB,
        FhaExchange,
        FWMSDHoldingAllExchangeDVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FHAENAME = AttributesEnum.FhaEname.index();
    public static final int FHAMVB = AttributesEnum.FhaMvB.index();
    public static final int FHAEXCHANGE = AttributesEnum.FhaExchange.index();
    public static final int FWMSDHOLDINGALLEXCHANGEDVO = AttributesEnum.FWMSDHoldingAllExchangeDVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSDHoldingAllExchangeVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute FhaEname.
     * @return the FhaEname
     */
    public String getFhaEname() {
        return (String) getAttributeInternal(FHAENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaMvB.
     * @return the FhaMvB
     */
    public BigDecimal getFhaMvB() {
        return (BigDecimal) getAttributeInternal(FHAMVB);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaExchange.
     * @return the FhaExchange
     */
    public Long getFhaExchange() {
        return (Long) getAttributeInternal(FHAEXCHANGE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FWMSDHoldingAllExchangeDVO.
     */
    public RowIterator getFWMSDHoldingAllExchangeDVO() {
        return (RowIterator) getAttributeInternal(FWMSDHOLDINGALLEXCHANGEDVO);
    }
}

