package com.ciobera.fwms.system.model.am;

import com.ciobera.fwms.system.model.am.common.SystemAM;
import com.ciobera.fwms.system.model.vo.FWMSBondCoupenVOImpl;
import com.ciobera.fwms.system.model.vo.FWMSProductVOImpl;
import com.ciobera.fwms.system.model.vo.FWMSProductVORowImpl;
import com.ciobera.fwms.system.model.vo.readonly.ProductIdSeqImpl;
import com.ciobera.fwms.system.model.vo.readonly.ProductIdSeqRowImpl;

import java.util.HashMap;
import java.util.Map;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 15 18:06:02 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SystemAMImpl extends ApplicationModuleImpl implements SystemAM {
    /**
     * This is the default constructor (do not remove).
     */
    public SystemAMImpl() {
    }

    private oracle.jbo.domain.Date getCurrentDate() {
        return new oracle.jbo.domain.Date(oracle.jbo
                                                .domain
                                                .Date
                                                .getCurrentDate());
    }

    /**
     * This method is called to update logged in user and date for various scenarios.
     * In Create Mode, WMSENTERUID, WMSENTERDATE is updated.
     * In Edit Mode, WMSLASTUPDATEID, WMSLASTUPDATEDATE is updated.
     * In case of Approve, WMSAPPROVEUID, WMSAPPROVEDATE is updated.
     * @param mode
     * @param updatedBy
     */
    public Map updateProductRecord(String mode, String updatedBy) {
        Map resultMap = new HashMap();
        FWMSProductVOImpl productVO = getFWMSProduct();
        if (productVO != null) {
            FWMSProductVORowImpl productRow = (FWMSProductVORowImpl) productVO.getCurrentRow();
            if (productRow != null) {
                if ("EDIT".equalsIgnoreCase(mode)) {
                    productRow.setWmsLastUpdateUid(updatedBy);
                    productRow.setWmsLastUpdateDate(getCurrentDate());
                }
                if ("CREATE".equalsIgnoreCase(mode)) {
                    ProductIdSeqImpl seqImpl = getProductIdSeq();
                    if (seqImpl != null) {
                        seqImpl.executeQuery();
                        ProductIdSeqRowImpl productVORowImpl = (ProductIdSeqRowImpl) seqImpl.first();
                        if (productVORowImpl != null) {
                            productRow.setWmsProductId(productVORowImpl.getMaxProductId());
                            productRow.setWmsEnterUid(updatedBy);
                            productRow.setWmsEnterDate(getCurrentDate());
                        }
                    }
                }
                if ("APPROVE".equalsIgnoreCase(mode)) {
                    productRow.setWmsApproveUid(updatedBy);
                    productRow.setWmsApproveDate(getCurrentDate());
                }
                this.getDBTransaction().commit();
                resultMap.put("RESP_CODE", "SUCCESS");
            }
        }
        return resultMap;
    }

    /**
     *  This method is called in the create mode of add stock popup load.
     *  This method executes empty row set on FWMSBondCoupen VO.
     */
    public void executeEmptyRowSetBondCoupen() {
        FWMSBondCoupenVOImpl bondCoupenVO = getFWMSBondCoupen();
        if (bondCoupenVO != null) {
            bondCoupenVO.executeEmptyRowSet();
        }
    }

    /**
     * Container's getter for FWMSProduct.
     * @return FWMSProduct
     */
    public FWMSProductVOImpl getFWMSProduct() {
        return (FWMSProductVOImpl) findViewObject("FWMSProduct");
    }

    /**
     * Container's getter for FWMSBondCoupen.
     * @return FWMSBondCoupen
     */
    public FWMSBondCoupenVOImpl getFWMSBondCoupen() {
        return (FWMSBondCoupenVOImpl) findViewObject("FWMSBondCoupen");
    }

    /**
     * Container's getter for FWMSProductVOToFWMSBondCoupen.
     * @return FWMSProductVOToFWMSBondCoupen
     */
    public ViewLinkImpl getFWMSProductVOToFWMSBondCoupen() {
        return (ViewLinkImpl) findViewLink("FWMSProductVOToFWMSBondCoupen");
    }

    /**
     * Container's getter for ProductIdSeq1.
     * @return ProductIdSeq1
     */
    public ProductIdSeqImpl getProductIdSeq() {
        return (ProductIdSeqImpl) findViewObject("ProductIdSeq");
    }
}

