package com.ciobera.fwms.system.model.eo;

import com.ciobera.fwms.system.model.vo.readonly.ProductIdSeqRowImpl;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 26 16:07:21 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSProductEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WmsProductType,
        WmsProductId,
        WmsProductName,
        WmsTicker,
        WmsRetuerCode,
        WmsBloombergCode,
        WmsIsinCode,
        WmsOtherCode,
        WmsOtherDesc,
        WmsPriceUpdate,
        WmsCountry,
        WmsCurrency,
        WmsStockExchange,
        WmsSector,
        WmsAsset,
        WmsBondIssueNo,
        WmsBondIssueDate,
        WmsBondMaturityDt,
        WmsBondUnitPrice,
        WmsBondCouponRate,
        WmsBondCouponFrequency,
        WmsBondDivisorDaysMonth,
        WmsBondDivisorDaysYear,
        WmsBondCoupon1stIntdate,
        WmsBondCoupon2ndIntdate,
        WmsBondCoupon3rdIntdate,
        WmsBondCoupon4thIntdate,
        WmsPutCallFlag,
        WmsPutCallExpiryDate,
        WmsPutCallLotsize,
        WmsPutCallSprice,
        WmsPutCallStatus,
        WmsMutualFundsIssue,
        WmsMutualInhouse3rdFlag,
        WmsMutualFundsClosdedOpen,
        WmsMutualFundsNavFlag,
        WmsComments,
        WmsStatus,
        WmsEnterUid,
        WmsEnterFpc,
        WmsEnterDate,
        WmsLastUpdateUid,
        WmsLastFpc,
        WmsLastUpdateDate,
        WmsApproveUid,
        WmsApproveFpc,
        WmsApproveDate,
        WmsMutualFundsValue,
        WmsMutualIbType,
        WmsSedol,
        FWMSBondCoupenEO,
        FWMSAsset,
        FWMSCountry,
        FWMSCurrency,
        FWMSSector,
        FWMSStockExchange,
        ProductIdSeq;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int WMSPRODUCTTYPE = AttributesEnum.WmsProductType.index();
    public static final int WMSPRODUCTID = AttributesEnum.WmsProductId.index();
    public static final int WMSPRODUCTNAME = AttributesEnum.WmsProductName.index();
    public static final int WMSTICKER = AttributesEnum.WmsTicker.index();
    public static final int WMSRETUERCODE = AttributesEnum.WmsRetuerCode.index();
    public static final int WMSBLOOMBERGCODE = AttributesEnum.WmsBloombergCode.index();
    public static final int WMSISINCODE = AttributesEnum.WmsIsinCode.index();
    public static final int WMSOTHERCODE = AttributesEnum.WmsOtherCode.index();
    public static final int WMSOTHERDESC = AttributesEnum.WmsOtherDesc.index();
    public static final int WMSPRICEUPDATE = AttributesEnum.WmsPriceUpdate.index();
    public static final int WMSCOUNTRY = AttributesEnum.WmsCountry.index();
    public static final int WMSCURRENCY = AttributesEnum.WmsCurrency.index();
    public static final int WMSSTOCKEXCHANGE = AttributesEnum.WmsStockExchange.index();
    public static final int WMSSECTOR = AttributesEnum.WmsSector.index();
    public static final int WMSASSET = AttributesEnum.WmsAsset.index();
    public static final int WMSBONDISSUENO = AttributesEnum.WmsBondIssueNo.index();
    public static final int WMSBONDISSUEDATE = AttributesEnum.WmsBondIssueDate.index();
    public static final int WMSBONDMATURITYDT = AttributesEnum.WmsBondMaturityDt.index();
    public static final int WMSBONDUNITPRICE = AttributesEnum.WmsBondUnitPrice.index();
    public static final int WMSBONDCOUPONRATE = AttributesEnum.WmsBondCouponRate.index();
    public static final int WMSBONDCOUPONFREQUENCY = AttributesEnum.WmsBondCouponFrequency.index();
    public static final int WMSBONDDIVISORDAYSMONTH = AttributesEnum.WmsBondDivisorDaysMonth.index();
    public static final int WMSBONDDIVISORDAYSYEAR = AttributesEnum.WmsBondDivisorDaysYear.index();
    public static final int WMSBONDCOUPON1STINTDATE = AttributesEnum.WmsBondCoupon1stIntdate.index();
    public static final int WMSBONDCOUPON2NDINTDATE = AttributesEnum.WmsBondCoupon2ndIntdate.index();
    public static final int WMSBONDCOUPON3RDINTDATE = AttributesEnum.WmsBondCoupon3rdIntdate.index();
    public static final int WMSBONDCOUPON4THINTDATE = AttributesEnum.WmsBondCoupon4thIntdate.index();
    public static final int WMSPUTCALLFLAG = AttributesEnum.WmsPutCallFlag.index();
    public static final int WMSPUTCALLEXPIRYDATE = AttributesEnum.WmsPutCallExpiryDate.index();
    public static final int WMSPUTCALLLOTSIZE = AttributesEnum.WmsPutCallLotsize.index();
    public static final int WMSPUTCALLSPRICE = AttributesEnum.WmsPutCallSprice.index();
    public static final int WMSPUTCALLSTATUS = AttributesEnum.WmsPutCallStatus.index();
    public static final int WMSMUTUALFUNDSISSUE = AttributesEnum.WmsMutualFundsIssue.index();
    public static final int WMSMUTUALINHOUSE3RDFLAG = AttributesEnum.WmsMutualInhouse3rdFlag.index();
    public static final int WMSMUTUALFUNDSCLOSDEDOPEN = AttributesEnum.WmsMutualFundsClosdedOpen.index();
    public static final int WMSMUTUALFUNDSNAVFLAG = AttributesEnum.WmsMutualFundsNavFlag.index();
    public static final int WMSCOMMENTS = AttributesEnum.WmsComments.index();
    public static final int WMSSTATUS = AttributesEnum.WmsStatus.index();
    public static final int WMSENTERUID = AttributesEnum.WmsEnterUid.index();
    public static final int WMSENTERFPC = AttributesEnum.WmsEnterFpc.index();
    public static final int WMSENTERDATE = AttributesEnum.WmsEnterDate.index();
    public static final int WMSLASTUPDATEUID = AttributesEnum.WmsLastUpdateUid.index();
    public static final int WMSLASTFPC = AttributesEnum.WmsLastFpc.index();
    public static final int WMSLASTUPDATEDATE = AttributesEnum.WmsLastUpdateDate.index();
    public static final int WMSAPPROVEUID = AttributesEnum.WmsApproveUid.index();
    public static final int WMSAPPROVEFPC = AttributesEnum.WmsApproveFpc.index();
    public static final int WMSAPPROVEDATE = AttributesEnum.WmsApproveDate.index();
    public static final int WMSMUTUALFUNDSVALUE = AttributesEnum.WmsMutualFundsValue.index();
    public static final int WMSMUTUALIBTYPE = AttributesEnum.WmsMutualIbType.index();
    public static final int WMSSEDOL = AttributesEnum.WmsSedol.index();
    public static final int FWMSBONDCOUPENEO = AttributesEnum.FWMSBondCoupenEO.index();
    public static final int FWMSASSET = AttributesEnum.FWMSAsset.index();
    public static final int FWMSCOUNTRY = AttributesEnum.FWMSCountry.index();
    public static final int FWMSCURRENCY = AttributesEnum.FWMSCurrency.index();
    public static final int FWMSSECTOR = AttributesEnum.FWMSSector.index();
    public static final int FWMSSTOCKEXCHANGE = AttributesEnum.FWMSStockExchange.index();
    public static final int PRODUCTIDSEQ = AttributesEnum.ProductIdSeq.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSProductEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.ciobera.fwms.system.model.eo.FWMSProductEO");
    }

    /**
     * Gets the attribute value for WmsProductType, using the alias name WmsProductType.
     * @return the value of WmsProductType
     */
    public String getWmsProductType() {
        return (String) getAttributeInternal(WMSPRODUCTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsProductType.
     * @param value value to set the WmsProductType
     */
    public void setWmsProductType(String value) {
        setAttributeInternal(WMSPRODUCTTYPE, value);
    }

    /**
     * Gets the attribute value for WmsProductId, using the alias name WmsProductId.
     * @return the value of WmsProductId
     */
    public Long getWmsProductId() {
        return (Long) getAttributeInternal(WMSPRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsProductId.
     * @param value value to set the WmsProductId
     */
    public void setWmsProductId(Long value) {
        setAttributeInternal(WMSPRODUCTID, value);
    }

    /**
     * Gets the attribute value for WmsProductName, using the alias name WmsProductName.
     * @return the value of WmsProductName
     */
    public String getWmsProductName() {
        return (String) getAttributeInternal(WMSPRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsProductName.
     * @param value value to set the WmsProductName
     */
    public void setWmsProductName(String value) {
        setAttributeInternal(WMSPRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for WmsTicker, using the alias name WmsTicker.
     * @return the value of WmsTicker
     */
    public String getWmsTicker() {
        return (String) getAttributeInternal(WMSTICKER);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsTicker.
     * @param value value to set the WmsTicker
     */
    public void setWmsTicker(String value) {
        setAttributeInternal(WMSTICKER, value);
    }

    /**
     * Gets the attribute value for WmsRetuerCode, using the alias name WmsRetuerCode.
     * @return the value of WmsRetuerCode
     */
    public String getWmsRetuerCode() {
        return (String) getAttributeInternal(WMSRETUERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsRetuerCode.
     * @param value value to set the WmsRetuerCode
     */
    public void setWmsRetuerCode(String value) {
        setAttributeInternal(WMSRETUERCODE, value);
    }

    /**
     * Gets the attribute value for WmsBloombergCode, using the alias name WmsBloombergCode.
     * @return the value of WmsBloombergCode
     */
    public String getWmsBloombergCode() {
        return (String) getAttributeInternal(WMSBLOOMBERGCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBloombergCode.
     * @param value value to set the WmsBloombergCode
     */
    public void setWmsBloombergCode(String value) {
        setAttributeInternal(WMSBLOOMBERGCODE, value);
    }

    /**
     * Gets the attribute value for WmsIsinCode, using the alias name WmsIsinCode.
     * @return the value of WmsIsinCode
     */
    public String getWmsIsinCode() {
        return (String) getAttributeInternal(WMSISINCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsIsinCode.
     * @param value value to set the WmsIsinCode
     */
    public void setWmsIsinCode(String value) {
        setAttributeInternal(WMSISINCODE, value);
    }

    /**
     * Gets the attribute value for WmsOtherCode, using the alias name WmsOtherCode.
     * @return the value of WmsOtherCode
     */
    public String getWmsOtherCode() {
        return (String) getAttributeInternal(WMSOTHERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsOtherCode.
     * @param value value to set the WmsOtherCode
     */
    public void setWmsOtherCode(String value) {
        setAttributeInternal(WMSOTHERCODE, value);
    }

    /**
     * Gets the attribute value for WmsOtherDesc, using the alias name WmsOtherDesc.
     * @return the value of WmsOtherDesc
     */
    public String getWmsOtherDesc() {
        return (String) getAttributeInternal(WMSOTHERDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsOtherDesc.
     * @param value value to set the WmsOtherDesc
     */
    public void setWmsOtherDesc(String value) {
        setAttributeInternal(WMSOTHERDESC, value);
    }

    /**
     * Gets the attribute value for WmsPriceUpdate, using the alias name WmsPriceUpdate.
     * @return the value of WmsPriceUpdate
     */
    public String getWmsPriceUpdate() {
        return (String) getAttributeInternal(WMSPRICEUPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsPriceUpdate.
     * @param value value to set the WmsPriceUpdate
     */
    public void setWmsPriceUpdate(String value) {
        setAttributeInternal(WMSPRICEUPDATE, value);
    }

    /**
     * Gets the attribute value for WmsCountry, using the alias name WmsCountry.
     * @return the value of WmsCountry
     */
    public Integer getWmsCountry() {
        return (Integer) getAttributeInternal(WMSCOUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsCountry.
     * @param value value to set the WmsCountry
     */
    public void setWmsCountry(Integer value) {
        setAttributeInternal(WMSCOUNTRY, value);
    }

    /**
     * Gets the attribute value for WmsCurrency, using the alias name WmsCurrency.
     * @return the value of WmsCurrency
     */
    public Integer getWmsCurrency() {
        return (Integer) getAttributeInternal(WMSCURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsCurrency.
     * @param value value to set the WmsCurrency
     */
    public void setWmsCurrency(Integer value) {
        setAttributeInternal(WMSCURRENCY, value);
    }

    /**
     * Gets the attribute value for WmsStockExchange, using the alias name WmsStockExchange.
     * @return the value of WmsStockExchange
     */
    public Integer getWmsStockExchange() {
        return (Integer) getAttributeInternal(WMSSTOCKEXCHANGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsStockExchange.
     * @param value value to set the WmsStockExchange
     */
    public void setWmsStockExchange(Integer value) {
        setAttributeInternal(WMSSTOCKEXCHANGE, value);
    }

    /**
     * Gets the attribute value for WmsSector, using the alias name WmsSector.
     * @return the value of WmsSector
     */
    public Integer getWmsSector() {
        return (Integer) getAttributeInternal(WMSSECTOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsSector.
     * @param value value to set the WmsSector
     */
    public void setWmsSector(Integer value) {
        setAttributeInternal(WMSSECTOR, value);
    }

    /**
     * Gets the attribute value for WmsAsset, using the alias name WmsAsset.
     * @return the value of WmsAsset
     */
    public Integer getWmsAsset() {
        return (Integer) getAttributeInternal(WMSASSET);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsAsset.
     * @param value value to set the WmsAsset
     */
    public void setWmsAsset(Integer value) {
        setAttributeInternal(WMSASSET, value);
    }

    /**
     * Gets the attribute value for WmsBondIssueNo, using the alias name WmsBondIssueNo.
     * @return the value of WmsBondIssueNo
     */
    public String getWmsBondIssueNo() {
        return (String) getAttributeInternal(WMSBONDISSUENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondIssueNo.
     * @param value value to set the WmsBondIssueNo
     */
    public void setWmsBondIssueNo(String value) {
        setAttributeInternal(WMSBONDISSUENO, value);
    }

    /**
     * Gets the attribute value for WmsBondIssueDate, using the alias name WmsBondIssueDate.
     * @return the value of WmsBondIssueDate
     */
    public Date getWmsBondIssueDate() {
        return (Date) getAttributeInternal(WMSBONDISSUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondIssueDate.
     * @param value value to set the WmsBondIssueDate
     */
    public void setWmsBondIssueDate(Date value) {
        setAttributeInternal(WMSBONDISSUEDATE, value);
    }

    /**
     * Gets the attribute value for WmsBondMaturityDt, using the alias name WmsBondMaturityDt.
     * @return the value of WmsBondMaturityDt
     */
    public Date getWmsBondMaturityDt() {
        return (Date) getAttributeInternal(WMSBONDMATURITYDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondMaturityDt.
     * @param value value to set the WmsBondMaturityDt
     */
    public void setWmsBondMaturityDt(Date value) {
        setAttributeInternal(WMSBONDMATURITYDT, value);
    }

    /**
     * Gets the attribute value for WmsBondUnitPrice, using the alias name WmsBondUnitPrice.
     * @return the value of WmsBondUnitPrice
     */
    public BigDecimal getWmsBondUnitPrice() {
        return (BigDecimal) getAttributeInternal(WMSBONDUNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondUnitPrice.
     * @param value value to set the WmsBondUnitPrice
     */
    public void setWmsBondUnitPrice(BigDecimal value) {
        setAttributeInternal(WMSBONDUNITPRICE, value);
    }

    /**
     * Gets the attribute value for WmsBondCouponRate, using the alias name WmsBondCouponRate.
     * @return the value of WmsBondCouponRate
     */
    public BigDecimal getWmsBondCouponRate() {
        return (BigDecimal) getAttributeInternal(WMSBONDCOUPONRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondCouponRate.
     * @param value value to set the WmsBondCouponRate
     */
    public void setWmsBondCouponRate(BigDecimal value) {
        setAttributeInternal(WMSBONDCOUPONRATE, value);
    }

    /**
     * Gets the attribute value for WmsBondCouponFrequency, using the alias name WmsBondCouponFrequency.
     * @return the value of WmsBondCouponFrequency
     */
    public String getWmsBondCouponFrequency() {
        return (String) getAttributeInternal(WMSBONDCOUPONFREQUENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondCouponFrequency.
     * @param value value to set the WmsBondCouponFrequency
     */
    public void setWmsBondCouponFrequency(String value) {
        setAttributeInternal(WMSBONDCOUPONFREQUENCY, value);
    }

    /**
     * Gets the attribute value for WmsBondDivisorDaysMonth, using the alias name WmsBondDivisorDaysMonth.
     * @return the value of WmsBondDivisorDaysMonth
     */
    public String getWmsBondDivisorDaysMonth() {
        return (String) getAttributeInternal(WMSBONDDIVISORDAYSMONTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondDivisorDaysMonth.
     * @param value value to set the WmsBondDivisorDaysMonth
     */
    public void setWmsBondDivisorDaysMonth(String value) {
        setAttributeInternal(WMSBONDDIVISORDAYSMONTH, value);
    }

    /**
     * Gets the attribute value for WmsBondDivisorDaysYear, using the alias name WmsBondDivisorDaysYear.
     * @return the value of WmsBondDivisorDaysYear
     */
    public Integer getWmsBondDivisorDaysYear() {
        return (Integer) getAttributeInternal(WMSBONDDIVISORDAYSYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondDivisorDaysYear.
     * @param value value to set the WmsBondDivisorDaysYear
     */
    public void setWmsBondDivisorDaysYear(Integer value) {
        setAttributeInternal(WMSBONDDIVISORDAYSYEAR, value);
    }

    /**
     * Gets the attribute value for WmsBondCoupon1stIntdate, using the alias name WmsBondCoupon1stIntdate.
     * @return the value of WmsBondCoupon1stIntdate
     */
    public String getWmsBondCoupon1stIntdate() {
        return (String) getAttributeInternal(WMSBONDCOUPON1STINTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondCoupon1stIntdate.
     * @param value value to set the WmsBondCoupon1stIntdate
     */
    public void setWmsBondCoupon1stIntdate(String value) {
        setAttributeInternal(WMSBONDCOUPON1STINTDATE, value);
    }

    /**
     * Gets the attribute value for WmsBondCoupon2ndIntdate, using the alias name WmsBondCoupon2ndIntdate.
     * @return the value of WmsBondCoupon2ndIntdate
     */
    public String getWmsBondCoupon2ndIntdate() {
        return (String) getAttributeInternal(WMSBONDCOUPON2NDINTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondCoupon2ndIntdate.
     * @param value value to set the WmsBondCoupon2ndIntdate
     */
    public void setWmsBondCoupon2ndIntdate(String value) {
        setAttributeInternal(WMSBONDCOUPON2NDINTDATE, value);
    }

    /**
     * Gets the attribute value for WmsBondCoupon3rdIntdate, using the alias name WmsBondCoupon3rdIntdate.
     * @return the value of WmsBondCoupon3rdIntdate
     */
    public String getWmsBondCoupon3rdIntdate() {
        return (String) getAttributeInternal(WMSBONDCOUPON3RDINTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondCoupon3rdIntdate.
     * @param value value to set the WmsBondCoupon3rdIntdate
     */
    public void setWmsBondCoupon3rdIntdate(String value) {
        setAttributeInternal(WMSBONDCOUPON3RDINTDATE, value);
    }

    /**
     * Gets the attribute value for WmsBondCoupon4thIntdate, using the alias name WmsBondCoupon4thIntdate.
     * @return the value of WmsBondCoupon4thIntdate
     */
    public String getWmsBondCoupon4thIntdate() {
        return (String) getAttributeInternal(WMSBONDCOUPON4THINTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsBondCoupon4thIntdate.
     * @param value value to set the WmsBondCoupon4thIntdate
     */
    public void setWmsBondCoupon4thIntdate(String value) {
        setAttributeInternal(WMSBONDCOUPON4THINTDATE, value);
    }

    /**
     * Gets the attribute value for WmsPutCallFlag, using the alias name WmsPutCallFlag.
     * @return the value of WmsPutCallFlag
     */
    public String getWmsPutCallFlag() {
        return (String) getAttributeInternal(WMSPUTCALLFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsPutCallFlag.
     * @param value value to set the WmsPutCallFlag
     */
    public void setWmsPutCallFlag(String value) {
        setAttributeInternal(WMSPUTCALLFLAG, value);
    }

    /**
     * Gets the attribute value for WmsPutCallExpiryDate, using the alias name WmsPutCallExpiryDate.
     * @return the value of WmsPutCallExpiryDate
     */
    public Date getWmsPutCallExpiryDate() {
        return (Date) getAttributeInternal(WMSPUTCALLEXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsPutCallExpiryDate.
     * @param value value to set the WmsPutCallExpiryDate
     */
    public void setWmsPutCallExpiryDate(Date value) {
        setAttributeInternal(WMSPUTCALLEXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for WmsPutCallLotsize, using the alias name WmsPutCallLotsize.
     * @return the value of WmsPutCallLotsize
     */
    public Long getWmsPutCallLotsize() {
        return (Long) getAttributeInternal(WMSPUTCALLLOTSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsPutCallLotsize.
     * @param value value to set the WmsPutCallLotsize
     */
    public void setWmsPutCallLotsize(Long value) {
        setAttributeInternal(WMSPUTCALLLOTSIZE, value);
    }

    /**
     * Gets the attribute value for WmsPutCallSprice, using the alias name WmsPutCallSprice.
     * @return the value of WmsPutCallSprice
     */
    public BigDecimal getWmsPutCallSprice() {
        return (BigDecimal) getAttributeInternal(WMSPUTCALLSPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsPutCallSprice.
     * @param value value to set the WmsPutCallSprice
     */
    public void setWmsPutCallSprice(BigDecimal value) {
        setAttributeInternal(WMSPUTCALLSPRICE, value);
    }

    /**
     * Gets the attribute value for WmsPutCallStatus, using the alias name WmsPutCallStatus.
     * @return the value of WmsPutCallStatus
     */
    public BigDecimal getWmsPutCallStatus() {
        return (BigDecimal) getAttributeInternal(WMSPUTCALLSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsPutCallStatus.
     * @param value value to set the WmsPutCallStatus
     */
    public void setWmsPutCallStatus(BigDecimal value) {
        setAttributeInternal(WMSPUTCALLSTATUS, value);
    }

    /**
     * Gets the attribute value for WmsMutualFundsIssue, using the alias name WmsMutualFundsIssue.
     * @return the value of WmsMutualFundsIssue
     */
    public String getWmsMutualFundsIssue() {
        return (String) getAttributeInternal(WMSMUTUALFUNDSISSUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsMutualFundsIssue.
     * @param value value to set the WmsMutualFundsIssue
     */
    public void setWmsMutualFundsIssue(String value) {
        setAttributeInternal(WMSMUTUALFUNDSISSUE, value);
    }

    /**
     * Gets the attribute value for WmsMutualInhouse3rdFlag, using the alias name WmsMutualInhouse3rdFlag.
     * @return the value of WmsMutualInhouse3rdFlag
     */
    public String getWmsMutualInhouse3rdFlag() {
        return (String) getAttributeInternal(WMSMUTUALINHOUSE3RDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsMutualInhouse3rdFlag.
     * @param value value to set the WmsMutualInhouse3rdFlag
     */
    public void setWmsMutualInhouse3rdFlag(String value) {
        setAttributeInternal(WMSMUTUALINHOUSE3RDFLAG, value);
    }

    /**
     * Gets the attribute value for WmsMutualFundsClosdedOpen, using the alias name WmsMutualFundsClosdedOpen.
     * @return the value of WmsMutualFundsClosdedOpen
     */
    public String getWmsMutualFundsClosdedOpen() {
        return (String) getAttributeInternal(WMSMUTUALFUNDSCLOSDEDOPEN);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsMutualFundsClosdedOpen.
     * @param value value to set the WmsMutualFundsClosdedOpen
     */
    public void setWmsMutualFundsClosdedOpen(String value) {
        setAttributeInternal(WMSMUTUALFUNDSCLOSDEDOPEN, value);
    }

    /**
     * Gets the attribute value for WmsMutualFundsNavFlag, using the alias name WmsMutualFundsNavFlag.
     * @return the value of WmsMutualFundsNavFlag
     */
    public String getWmsMutualFundsNavFlag() {
        return (String) getAttributeInternal(WMSMUTUALFUNDSNAVFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsMutualFundsNavFlag.
     * @param value value to set the WmsMutualFundsNavFlag
     */
    public void setWmsMutualFundsNavFlag(String value) {
        setAttributeInternal(WMSMUTUALFUNDSNAVFLAG, value);
    }

    /**
     * Gets the attribute value for WmsComments, using the alias name WmsComments.
     * @return the value of WmsComments
     */
    public String getWmsComments() {
        return (String) getAttributeInternal(WMSCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsComments.
     * @param value value to set the WmsComments
     */
    public void setWmsComments(String value) {
        setAttributeInternal(WMSCOMMENTS, value);
    }

    /**
     * Gets the attribute value for WmsStatus, using the alias name WmsStatus.
     * @return the value of WmsStatus
     */
    public String getWmsStatus() {
        return (String) getAttributeInternal(WMSSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsStatus.
     * @param value value to set the WmsStatus
     */
    public void setWmsStatus(String value) {
        setAttributeInternal(WMSSTATUS, value);
    }

    /**
     * Gets the attribute value for WmsEnterUid, using the alias name WmsEnterUid.
     * @return the value of WmsEnterUid
     */
    public String getWmsEnterUid() {
        return (String) getAttributeInternal(WMSENTERUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsEnterUid.
     * @param value value to set the WmsEnterUid
     */
    public void setWmsEnterUid(String value) {
        setAttributeInternal(WMSENTERUID, value);
    }

    /**
     * Gets the attribute value for WmsEnterFpc, using the alias name WmsEnterFpc.
     * @return the value of WmsEnterFpc
     */
    public String getWmsEnterFpc() {
        return (String) getAttributeInternal(WMSENTERFPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsEnterFpc.
     * @param value value to set the WmsEnterFpc
     */
    public void setWmsEnterFpc(String value) {
        setAttributeInternal(WMSENTERFPC, value);
    }

    /**
     * Gets the attribute value for WmsEnterDate, using the alias name WmsEnterDate.
     * @return the value of WmsEnterDate
     */
    public Date getWmsEnterDate() {
        return (Date) getAttributeInternal(WMSENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsEnterDate.
     * @param value value to set the WmsEnterDate
     */
    public void setWmsEnterDate(Date value) {
        setAttributeInternal(WMSENTERDATE, value);
    }

    /**
     * Gets the attribute value for WmsLastUpdateUid, using the alias name WmsLastUpdateUid.
     * @return the value of WmsLastUpdateUid
     */
    public String getWmsLastUpdateUid() {
        return (String) getAttributeInternal(WMSLASTUPDATEUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsLastUpdateUid.
     * @param value value to set the WmsLastUpdateUid
     */
    public void setWmsLastUpdateUid(String value) {
        setAttributeInternal(WMSLASTUPDATEUID, value);
    }

    /**
     * Gets the attribute value for WmsLastFpc, using the alias name WmsLastFpc.
     * @return the value of WmsLastFpc
     */
    public String getWmsLastFpc() {
        return (String) getAttributeInternal(WMSLASTFPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsLastFpc.
     * @param value value to set the WmsLastFpc
     */
    public void setWmsLastFpc(String value) {
        setAttributeInternal(WMSLASTFPC, value);
    }

    /**
     * Gets the attribute value for WmsLastUpdateDate, using the alias name WmsLastUpdateDate.
     * @return the value of WmsLastUpdateDate
     */
    public Date getWmsLastUpdateDate() {
        return (Date) getAttributeInternal(WMSLASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsLastUpdateDate.
     * @param value value to set the WmsLastUpdateDate
     */
    public void setWmsLastUpdateDate(Date value) {
        setAttributeInternal(WMSLASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for WmsApproveUid, using the alias name WmsApproveUid.
     * @return the value of WmsApproveUid
     */
    public String getWmsApproveUid() {
        return (String) getAttributeInternal(WMSAPPROVEUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsApproveUid.
     * @param value value to set the WmsApproveUid
     */
    public void setWmsApproveUid(String value) {
        setAttributeInternal(WMSAPPROVEUID, value);
    }

    /**
     * Gets the attribute value for WmsApproveFpc, using the alias name WmsApproveFpc.
     * @return the value of WmsApproveFpc
     */
    public String getWmsApproveFpc() {
        return (String) getAttributeInternal(WMSAPPROVEFPC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsApproveFpc.
     * @param value value to set the WmsApproveFpc
     */
    public void setWmsApproveFpc(String value) {
        setAttributeInternal(WMSAPPROVEFPC, value);
    }

    /**
     * Gets the attribute value for WmsApproveDate, using the alias name WmsApproveDate.
     * @return the value of WmsApproveDate
     */
    public Date getWmsApproveDate() {
        return (Date) getAttributeInternal(WMSAPPROVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsApproveDate.
     * @param value value to set the WmsApproveDate
     */
    public void setWmsApproveDate(Date value) {
        setAttributeInternal(WMSAPPROVEDATE, value);
    }

    /**
     * Gets the attribute value for WmsMutualFundsValue, using the alias name WmsMutualFundsValue.
     * @return the value of WmsMutualFundsValue
     */
    public BigDecimal getWmsMutualFundsValue() {
        return (BigDecimal) getAttributeInternal(WMSMUTUALFUNDSVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsMutualFundsValue.
     * @param value value to set the WmsMutualFundsValue
     */
    public void setWmsMutualFundsValue(BigDecimal value) {
        setAttributeInternal(WMSMUTUALFUNDSVALUE, value);
    }

    /**
     * Gets the attribute value for WmsMutualIbType, using the alias name WmsMutualIbType.
     * @return the value of WmsMutualIbType
     */
    public String getWmsMutualIbType() {
        return (String) getAttributeInternal(WMSMUTUALIBTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsMutualIbType.
     * @param value value to set the WmsMutualIbType
     */
    public void setWmsMutualIbType(String value) {
        setAttributeInternal(WMSMUTUALIBTYPE, value);
    }

    /**
     * Gets the attribute value for WmsSedol, using the alias name WmsSedol.
     * @return the value of WmsSedol
     */
    public String getWmsSedol() {
        return (String) getAttributeInternal(WMSSEDOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for WmsSedol.
     * @param value value to set the WmsSedol
     */
    public void setWmsSedol(String value) {
        setAttributeInternal(WMSSEDOL, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getFWMSBondCoupenEO() {
        return (RowIterator) getAttributeInternal(FWMSBONDCOUPENEO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FWMSAsset.
     */
    public RowSet getFWMSAsset() {
        return (RowSet) getAttributeInternal(FWMSASSET);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FWMSCountry.
     */
    public RowSet getFWMSCountry() {
        return (RowSet) getAttributeInternal(FWMSCOUNTRY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FWMSCurrency.
     */
    public RowSet getFWMSCurrency() {
        return (RowSet) getAttributeInternal(FWMSCURRENCY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FWMSSector.
     */
    public RowSet getFWMSSector() {
        return (RowSet) getAttributeInternal(FWMSSECTOR);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FWMSStockExchange.
     */
    public RowSet getFWMSStockExchange() {
        return (RowSet) getAttributeInternal(FWMSSTOCKEXCHANGE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductIdSeq.
     */
    public RowSet getProductIdSeq() {
        return (RowSet) getAttributeInternal(PRODUCTIDSEQ);
    }


    /**
     * @param wmsProductId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long wmsProductId) {
        return new Key(new Object[] { wmsProductId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            RowSet seqForThisProduct = getProductIdSeq();
            ProductIdSeqRowImpl nextSeqNoRow = (ProductIdSeqRowImpl) seqForThisProduct.next();
            Long next_seq = nextSeqNoRow.getMaxProductId();
            setWmsProductId(next_seq);
            seqForThisProduct.closeRowSet();
        }
        super.doDML(operation, e);
    }
}

