--CREATE TABLE FWMS_ORDER_BOOK;
CREATE TABLE FWMS_ORDER_BOOK (
FOB_NO		NUMBER(10),
FOB_DATE	DATE,
FOB_TIME	VARCHAR2(20),
FOB_B_S		VARCHAR2(10),
FOB_L_S		VARCHAR2(10),
FOB_SHARE_CLASS	VARCHAR2(25),
FOB_FUND	NUMBER(10),
FOB_BROKER	NUMBER(10),
FOB_CLIENT	NUMBER(10),
FOB_STOCK	NUMBER(10),
FOB_STOCK_NAME	VARCHAR2(100),
FOB_TICKER	VARCHAR2(30),
FOB_L_M		VARCHAR2(15),
FOB_QTY		NUMBER(20,3),
FOB_PRICE	NUMBER(20,3),
FOB_VALUE	NUMBER(20,3),
FOB_MPRICE	NUMBER(20,3),
FOB_BQTY	NUMBER(20,3),
FOB_BPRICE	NUMBER(20,3),
FOB_AQTY	NUMBER(20,3),
FOB_APRICE	NUMBER(20,3),
FOB_HIGH	NUMBER(20,3),
FOB_LOW		NUMBER(20,3),
FOB_VOLUME	NUMBER(20,3),
FOB_BROKER_QTY		NUMBER(20,3),
FOB_BROKER_CASH		NUMBER(20,3),
FOB_MARGIN_AMT	NUMBER(20,3),
FOB_OSTATUS	VARCHAR2(25),
FOB_EQTY	NUMBER(20,3),
FOB_EPRICE	NUMBER(20,3),
WMS_ENTER_UID                                      VARCHAR2(20),
WMS_ENTER_FPC                                      VARCHAR2(30),
WMS_ENTER_DATE                                     DATE,
WMS_LAST_UPDATE_UID                                VARCHAR2(20),
WMS_LAST_FPC                                       VARCHAR2(30),
WMS_LAST_UPDATE_DATE                               DATE,
WMS_APPROVE_UID                                    VARCHAR2(20),
WMS_APPROVE_FPC                                    VARCHAR2(30),
WMS_APPROVE_DATE                                   DATE
);

--CREATE TABLE FWMS_BROKER;
CREATE TABLE FWMS_BROKER (
 WMS_BROKER_ID                             NUMBER(15),
 WMS_BROKER_NAME                           VARCHAR2(75)
 );

--CREATE TABLE FWMS_MUTUAL_FUNDS;
CREATE TABLE FWMS_MUTUAL_FUNDS (
 WMS_MFUND_ID                               NUMBER(15),
 WMS_MFUND_NAME                             VARCHAR2(75),
 WMS_MFUND_SHORT_NAME                       VARCHAR2(10)
 );
 
--CREATE TABLE FWMS_MARKET_PRICE_LIVE;
CREATE TABLE FWMS_MARKET_PRICE_LIVE (
 WMS_DATE                   DATE,
 WMS_STOCK_ID               NUMBER(15),
 WMS_PREVIOUS_CLOSE         NUMBER(28,8),
 WMS_HIGH                   NUMBER(28,8),
 WMS_LOW                    NUMBER(28,8),
 WMS_CLOSE_PRICE            NUMBER(28,8),
 WMS_VOL                    NUMBER(28,3),
 WMS_BQTY					NUMBER(20,3),
 WMS_BPRICE					NUMBER(20,3),
 WMS_AQTY					NUMBER(20,3),
 WMS_APRICE					NUMBER(20,3)
 );
 
 --CREATE TABLE FWMS_CLIENT_SUB;
CREATE TABLE FWMS_CLIENT_SUB(
WMS_SUB_CLIENT 				NUMBER(25),
WMS_SUB_CLIENT_NAME        	VARCHAR2(100)
);
 
--INSERT INTO FWMS_BROKER
INSERT INTO FWMS_BROKER(WMS_BROKER_ID, WMS_BROKER_NAME)  VALUES (99001,'BROKER 1');
INSERT INTO FWMS_BROKER(WMS_BROKER_ID, WMS_BROKER_NAME) VALUES (99002,'BROKER 2');

--INSERT INTO FWMS_MUTUAL_FUNDS
INSERT INTO FWMS_MUTUAL_FUNDS(WMS_MFUND_ID, WMS_MFUND_NAME, WMS_MFUND_SHORT_NAME) VALUES (1,'FUND 1','F1');
INSERT INTO FWMS_MUTUAL_FUNDS(WMS_MFUND_ID, WMS_MFUND_NAME, WMS_MFUND_SHORT_NAME) VALUES (2,'FUND 2','F2');
INSERT INTO FWMS_MUTUAL_FUNDS(WMS_MFUND_ID, WMS_MFUND_NAME, WMS_MFUND_SHORT_NAME) VALUES (3,'FUND 3','F4'); 

--INSERT INTO FWMS_CLIENT_SUB
INSERT INTO FWMS_CLIENT_SUB(WMS_SUB_CLIENT, WMS_SUB_CLIENT_NAME) VALUES (1,'SRINI');
INSERT INTO FWMS_CLIENT_SUB(WMS_SUB_CLIENT, WMS_SUB_CLIENT_NAME) VALUES (2,'RAJ');
INSERT INTO FWMS_CLIENT_SUB(WMS_SUB_CLIENT, WMS_SUB_CLIENT_NAME) VALUES (3,'Sajeev');



