















/*
 * This is a generated file. Do not edit this file!
 */
package com.ciobera.fwms.utils.auth;

import java.util.Map;
import java.beans.BeanInfo;

import java.beans.BeanDescriptor;
import java.beans.MethodDescriptor;
import java.beans.PropertyDescriptor;
import java.beans.ParameterDescriptor;
import java.beans.EventSetDescriptor;
import java.beans.IntrospectionException;

import weblogic.management.internal.mbean.BeanInfoBinder;
import weblogic.management.internal.mbean.BeanInfoImpl;
import weblogic.management.internal.mbean.BeanInfoHelper;

import weblogic.management.commo.RequiredModelMBeanWrapper;

import com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean;

/**
 * @copyright Copyright (c) 2003,2014, Oracle and/or its affiliates. All rights reserved.
 * @author Copyright (c) 2003,2014, Oracle and/or its affiliates. All rights reserved.
 * @version 0.1
 */
public class IFWMSAuthenticationMBeanImplBeanInfo
  extends weblogic.management.security.authentication.AuthenticatorMBeanImplBeanInfo
{

  public IFWMSAuthenticationMBeanImplBeanInfo(boolean readOnly, String targetVersion)
      throws IntrospectionException {
    super(readOnly, targetVersion);
  }
  // constructor
  public IFWMSAuthenticationMBeanImplBeanInfo()
    throws IntrospectionException {

  }


  public static final Class INTERFACE_CLASS = com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class;


  protected BeanDescriptor buildBeanDescriptor() {

    Class beanClass = null;
    try {
      beanClass = Class.forName("com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBeanImpl");
    } catch (Throwable ignore) {
      beanClass = INTERFACE_CLASS;
    }
    
    BeanDescriptor beanDescriptor =
      new BeanDescriptor(  beanClass, null /*customizer*/ );

    beanDescriptor.setValue("dynamic",Boolean.TRUE);
     beanDescriptor.setValue("package","com.ciobera.fwms.utils.auth");
    String description = new String(
          
           "No description provided. " +  ""    ).intern();
    beanDescriptor.setShortDescription(description);
    beanDescriptor.setValue("description", description);
    beanDescriptor.setValue("interfaceclassname",  "com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean");
    beanDescriptor.setValue("generatedByWLSInfoBinder", Boolean.TRUE);

    return beanDescriptor;
  }

  /**
   * Get the attribute infos for this class and all of it parent
   * classes combined.
   *
   * @param descriptors the set to add you descriptors to.
   */
  protected void buildPropertyDescriptors( Map descriptors )
         throws IntrospectionException {
    PropertyDescriptor currentResult = null;
    // PROPERTY DbAuthPassword
    {
    if ( !descriptors.containsKey("DbAuthPassword"))
    {
      String getterName = "getDbAuthPassword";
      String setterName = null;
      if (!readOnly)
        setterName = "setDbAuthPassword";
      currentResult =
        new PropertyDescriptor( "DbAuthPassword",
             com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class,
             getterName,
             setterName);
      descriptors.put( "DbAuthPassword", currentResult );
      currentResult.setValue("description",     
           "No description provided. " +  "");
 // default = "hr"
     setPropertyDescriptorDefault(currentResult, "hr");
        currentResult.setValue("dynamic", Boolean.FALSE);
     currentResult.setValue("owner", "");
    }
    }
    // PROPERTY DbAuthUrl
    {
    if ( !descriptors.containsKey("DbAuthUrl"))
    {
      String getterName = "getDbAuthUrl";
      String setterName = null;
      if (!readOnly)
        setterName = "setDbAuthUrl";
      currentResult =
        new PropertyDescriptor( "DbAuthUrl",
             com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class,
             getterName,
             setterName);
      descriptors.put( "DbAuthUrl", currentResult );
      currentResult.setValue("description",     
           "No description provided. " +  "");
 // default = "jdbc:oracle:thin:@localhost:1521:orcl"
     setPropertyDescriptorDefault(currentResult, "jdbc:oracle:thin:@localhost:1521:orcl");
        currentResult.setValue("dynamic", Boolean.FALSE);
     currentResult.setValue("owner", "");
    }
    }
    // PROPERTY DbAuthUsername
    {
    if ( !descriptors.containsKey("DbAuthUsername"))
    {
      String getterName = "getDbAuthUsername";
      String setterName = null;
      if (!readOnly)
        setterName = "setDbAuthUsername";
      currentResult =
        new PropertyDescriptor( "DbAuthUsername",
             com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class,
             getterName,
             setterName);
      descriptors.put( "DbAuthUsername", currentResult );
      currentResult.setValue("description",     
           "No description provided. " +  "");
 // default = "hr"
     setPropertyDescriptorDefault(currentResult, "hr");
        currentResult.setValue("dynamic", Boolean.FALSE);
     currentResult.setValue("owner", "");
    }
    }
    // PROPERTY Description
    {
    if ( !descriptors.containsKey("Description"))
    {
      String getterName = "getDescription";
      String setterName = null;
      currentResult =
        new PropertyDescriptor( "Description",
             com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class,
             getterName,
             setterName);
      descriptors.put( "Description", currentResult );
      currentResult.setValue("description",     
           "No description provided. " +  "");
 // default = "Authentication Provider"
     setPropertyDescriptorDefault(currentResult, "Authentication Provider");
        currentResult.setValue("dynamic", Boolean.FALSE);
     currentResult.setValue("owner", "");
    }
    }
    // PROPERTY Name
    {
    if ( !descriptors.containsKey("Name"))
    {
      String getterName = "getName";
      String setterName = null;
      currentResult =
        new PropertyDescriptor( "Name",
             com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class,
             getterName,
             setterName);
      descriptors.put( "Name", currentResult );
      currentResult.setValue("description",     
           " " +  "");
 // default = "IFWMSAuthentication"
     setPropertyDescriptorDefault(currentResult, "IFWMSAuthentication");
        currentResult.setValue("dynamic", Boolean.FALSE);
     currentResult.setValue("owner", "RealmAdministrator");
      currentResult.setValue("VisibleToPartitions","ALWAYS");
      currentResult.setValue("owner","RealmAdministrator");
    }
    }
    // PROPERTY ProviderClassName
    {
    if ( !descriptors.containsKey("ProviderClassName"))
    {
      String getterName = "getProviderClassName";
      String setterName = null;
      currentResult =
        new PropertyDescriptor( "ProviderClassName",
             com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class,
             getterName,
             setterName);
      descriptors.put( "ProviderClassName", currentResult );
      currentResult.setValue("description",     
           "No description provided. " +  "");
 // default = "com.ciobera.fwms.utils.auth.db.IFWMSAuthenticationProviderImpl"
     setPropertyDescriptorDefault(currentResult, "com.ciobera.fwms.utils.auth.db.IFWMSAuthenticationProviderImpl");
        currentResult.setValue("dynamic", Boolean.FALSE);
     currentResult.setValue("owner", "");
    }
    }
    // PROPERTY Realm
    {
    if ( !descriptors.containsKey("Realm"))
    {
      String getterName = "getRealm";
      String setterName = null;
      currentResult =
        new PropertyDescriptor( "Realm",
             com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class,
             getterName,
             setterName);
      descriptors.put( "Realm", currentResult );
      currentResult.setValue("description",     
           "Returns the realm that contains this security provider. " + 
           "Returns null if this security provider is not contained by a realm. " +  "");
      currentResult.setValue("relationship", "reference");
         currentResult.setValue("transient", Boolean.TRUE);
     currentResult.setValue("dynamic", Boolean.FALSE);
     }
    }
    // PROPERTY Version
    {
    if ( !descriptors.containsKey("Version"))
    {
      String getterName = "getVersion";
      String setterName = null;
      currentResult =
        new PropertyDescriptor( "Version",
             com.ciobera.fwms.utils.auth.IFWMSAuthenticationMBean.class,
             getterName,
             setterName);
      descriptors.put( "Version", currentResult );
      currentResult.setValue("description",     
           "No description provided. " +  "");
 // default = "1.0"
     setPropertyDescriptorDefault(currentResult, "1.0");
        currentResult.setValue("dynamic", Boolean.FALSE);
     currentResult.setValue("owner", "");
    }
    }
    super.buildPropertyDescriptors( descriptors );
  }


  /**
   * Get the method infos for a subset of the overall methods types.
   *
   */
  private void fillinFactoryMethodInfos( Map descriptors )
         throws IntrospectionException,
                java.lang.NoSuchMethodException {

    MethodDescriptor currentResult;

  }

  /**
   * Get the method infos for a subset of the overall methods types.
   *
   */
  private void fillinCollectionMethodInfos( Map descriptors )
         throws IntrospectionException,
                java.lang.NoSuchMethodException {

    MethodDescriptor currentResult;

  }

  /**
   * Get the method infos for a subset of the overall methods types.
   *
   */
  private void fillinFinderMethodInfos( Map descriptors )
         throws IntrospectionException,
                java.lang.NoSuchMethodException {

    MethodDescriptor currentResult;

  }

  /**
   * Get the method infos for a subset of the overall methods types.
   *
   */
  private void fillinOperationMethodInfos( Map descriptors )
         throws IntrospectionException,
                java.lang.NoSuchMethodException {

    MethodDescriptor currentResult;

  }

  /**
   * Get the method infos for this class and all of it parent
   * classes combined.
   *
   * @param descriptors the set to add to.
   */
  protected void buildMethodDescriptors( Map descriptors )
         throws IntrospectionException,
                java.lang.NoSuchMethodException {

    fillinFinderMethodInfos(descriptors);
    if ( !readOnly ) {
      fillinCollectionMethodInfos(descriptors);
      fillinFactoryMethodInfos(descriptors);
    }
    fillinOperationMethodInfos(descriptors);
     super.buildMethodDescriptors(descriptors);
  }

  /**
    * Get the event infos for this class and all of it parent
    * classes combined.
    *
    * @param descriptors the set to add to.
    */
  protected void buildEventSetDescriptors(  Map descriptors )
       throws IntrospectionException {
    // TODO: this is not yet implemented
  }
}
