package com.ciobera.fwms.common.model.vo;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 12 16:27:01 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSUsersUpdateVORowImpl extends ViewRowImpl {
    public static final int ENTITY_FWMSUSERSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WmsUserSno,
        WmsCreateDate,
        WmsEmployeeNo,
        WmsName,
        WmsUserId,
        WmsUserPassword,
        WmsGroup,
        WmsGroupPrevilige,
        WmsPreviligeFlag,
        WmsExpiryDays,
        WmsLastLogin,
        WmsLastPasswordChange,
        WmsBlock,
        WmsStatus,
        WmsStatusCdate,
        WmsRemarks,
        WmsEnterUid,
        WmsEnterFpc,
        WmsEnterDate,
        WmsLastUpdateUid,
        WmsLastFpc,
        WmsLastUpdateDate,
        WmsApproveUid,
        WmsApproveFpc,
        WmsApproveDate,
        WmsComments,
        WmsEmail,
        WmsCompId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int WMSUSERSNO = AttributesEnum.WmsUserSno.index();
    public static final int WMSCREATEDATE = AttributesEnum.WmsCreateDate.index();
    public static final int WMSEMPLOYEENO = AttributesEnum.WmsEmployeeNo.index();
    public static final int WMSNAME = AttributesEnum.WmsName.index();
    public static final int WMSUSERID = AttributesEnum.WmsUserId.index();
    public static final int WMSUSERPASSWORD = AttributesEnum.WmsUserPassword.index();
    public static final int WMSGROUP = AttributesEnum.WmsGroup.index();
    public static final int WMSGROUPPREVILIGE = AttributesEnum.WmsGroupPrevilige.index();
    public static final int WMSPREVILIGEFLAG = AttributesEnum.WmsPreviligeFlag.index();
    public static final int WMSEXPIRYDAYS = AttributesEnum.WmsExpiryDays.index();
    public static final int WMSLASTLOGIN = AttributesEnum.WmsLastLogin.index();
    public static final int WMSLASTPASSWORDCHANGE = AttributesEnum.WmsLastPasswordChange.index();
    public static final int WMSBLOCK = AttributesEnum.WmsBlock.index();
    public static final int WMSSTATUS = AttributesEnum.WmsStatus.index();
    public static final int WMSSTATUSCDATE = AttributesEnum.WmsStatusCdate.index();
    public static final int WMSREMARKS = AttributesEnum.WmsRemarks.index();
    public static final int WMSENTERUID = AttributesEnum.WmsEnterUid.index();
    public static final int WMSENTERFPC = AttributesEnum.WmsEnterFpc.index();
    public static final int WMSENTERDATE = AttributesEnum.WmsEnterDate.index();
    public static final int WMSLASTUPDATEUID = AttributesEnum.WmsLastUpdateUid.index();
    public static final int WMSLASTFPC = AttributesEnum.WmsLastFpc.index();
    public static final int WMSLASTUPDATEDATE = AttributesEnum.WmsLastUpdateDate.index();
    public static final int WMSAPPROVEUID = AttributesEnum.WmsApproveUid.index();
    public static final int WMSAPPROVEFPC = AttributesEnum.WmsApproveFpc.index();
    public static final int WMSAPPROVEDATE = AttributesEnum.WmsApproveDate.index();
    public static final int WMSCOMMENTS = AttributesEnum.WmsComments.index();
    public static final int WMSEMAIL = AttributesEnum.WmsEmail.index();
    public static final int WMSCOMPID = AttributesEnum.WmsCompId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSUsersUpdateVORowImpl() {
    }

    /**
     * Gets FWMSUsersEO entity object.
     * @return the FWMSUsersEO
     */
    public EntityImpl getFWMSUsersEO() {
        return (EntityImpl) getEntity(ENTITY_FWMSUSERSEO);
    }

    /**
     * Gets the attribute value for WMS_USER_SNO using the alias name WmsUserSno.
     * @return the WMS_USER_SNO
     */
    public Long getWmsUserSno() {
        return (Long) getAttributeInternal(WMSUSERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_USER_SNO using the alias name WmsUserSno.
     * @param value value to set the WMS_USER_SNO
     */
    public void setWmsUserSno(Long value) {
        setAttributeInternal(WMSUSERSNO, value);
    }

    /**
     * Gets the attribute value for WMS_CREATE_DATE using the alias name WmsCreateDate.
     * @return the WMS_CREATE_DATE
     */
    public Timestamp getWmsCreateDate() {
        return (Timestamp) getAttributeInternal(WMSCREATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_CREATE_DATE using the alias name WmsCreateDate.
     * @param value value to set the WMS_CREATE_DATE
     */
    public void setWmsCreateDate(Timestamp value) {
        setAttributeInternal(WMSCREATEDATE, value);
    }

    /**
     * Gets the attribute value for WMS_EMPLOYEE_NO using the alias name WmsEmployeeNo.
     * @return the WMS_EMPLOYEE_NO
     */
    public Long getWmsEmployeeNo() {
        return (Long) getAttributeInternal(WMSEMPLOYEENO);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_EMPLOYEE_NO using the alias name WmsEmployeeNo.
     * @param value value to set the WMS_EMPLOYEE_NO
     */
    public void setWmsEmployeeNo(Long value) {
        setAttributeInternal(WMSEMPLOYEENO, value);
    }

    /**
     * Gets the attribute value for WMS_NAME using the alias name WmsName.
     * @return the WMS_NAME
     */
    public String getWmsName() {
        return (String) getAttributeInternal(WMSNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_NAME using the alias name WmsName.
     * @param value value to set the WMS_NAME
     */
    public void setWmsName(String value) {
        setAttributeInternal(WMSNAME, value);
    }

    /**
     * Gets the attribute value for WMS_USER_ID using the alias name WmsUserId.
     * @return the WMS_USER_ID
     */
    public String getWmsUserId() {
        return (String) getAttributeInternal(WMSUSERID);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_USER_ID using the alias name WmsUserId.
     * @param value value to set the WMS_USER_ID
     */
    public void setWmsUserId(String value) {
        setAttributeInternal(WMSUSERID, value);
    }

    /**
     * Gets the attribute value for WMS_USER_PASSWORD using the alias name WmsUserPassword.
     * @return the WMS_USER_PASSWORD
     */
    public String getWmsUserPassword() {
        return (String) getAttributeInternal(WMSUSERPASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_USER_PASSWORD using the alias name WmsUserPassword.
     * @param value value to set the WMS_USER_PASSWORD
     */
    public void setWmsUserPassword(String value) {
        setAttributeInternal(WMSUSERPASSWORD, value);
    }

    /**
     * Gets the attribute value for WMS_GROUP using the alias name WmsGroup.
     * @return the WMS_GROUP
     */
    public Integer getWmsGroup() {
        return (Integer) getAttributeInternal(WMSGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_GROUP using the alias name WmsGroup.
     * @param value value to set the WMS_GROUP
     */
    public void setWmsGroup(Integer value) {
        setAttributeInternal(WMSGROUP, value);
    }

    /**
     * Gets the attribute value for WMS_GROUP_PREVILIGE using the alias name WmsGroupPrevilige.
     * @return the WMS_GROUP_PREVILIGE
     */
    public Integer getWmsGroupPrevilige() {
        return (Integer) getAttributeInternal(WMSGROUPPREVILIGE);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_GROUP_PREVILIGE using the alias name WmsGroupPrevilige.
     * @param value value to set the WMS_GROUP_PREVILIGE
     */
    public void setWmsGroupPrevilige(Integer value) {
        setAttributeInternal(WMSGROUPPREVILIGE, value);
    }

    /**
     * Gets the attribute value for WMS_PREVILIGE_FLAG using the alias name WmsPreviligeFlag.
     * @return the WMS_PREVILIGE_FLAG
     */
    public Integer getWmsPreviligeFlag() {
        return (Integer) getAttributeInternal(WMSPREVILIGEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_PREVILIGE_FLAG using the alias name WmsPreviligeFlag.
     * @param value value to set the WMS_PREVILIGE_FLAG
     */
    public void setWmsPreviligeFlag(Integer value) {
        setAttributeInternal(WMSPREVILIGEFLAG, value);
    }

    /**
     * Gets the attribute value for WMS_EXPIRY_DAYS using the alias name WmsExpiryDays.
     * @return the WMS_EXPIRY_DAYS
     */
    public Integer getWmsExpiryDays() {
        return (Integer) getAttributeInternal(WMSEXPIRYDAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_EXPIRY_DAYS using the alias name WmsExpiryDays.
     * @param value value to set the WMS_EXPIRY_DAYS
     */
    public void setWmsExpiryDays(Integer value) {
        setAttributeInternal(WMSEXPIRYDAYS, value);
    }

    /**
     * Gets the attribute value for WMS_LAST_LOGIN using the alias name WmsLastLogin.
     * @return the WMS_LAST_LOGIN
     */
    public Timestamp getWmsLastLogin() {
        return (Timestamp) getAttributeInternal(WMSLASTLOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_LAST_LOGIN using the alias name WmsLastLogin.
     * @param value value to set the WMS_LAST_LOGIN
     */
    public void setWmsLastLogin(Timestamp value) {
        setAttributeInternal(WMSLASTLOGIN, value);
    }

    /**
     * Gets the attribute value for WMS_LAST_PASSWORD_CHANGE using the alias name WmsLastPasswordChange.
     * @return the WMS_LAST_PASSWORD_CHANGE
     */
    public Timestamp getWmsLastPasswordChange() {
        return (Timestamp) getAttributeInternal(WMSLASTPASSWORDCHANGE);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_LAST_PASSWORD_CHANGE using the alias name WmsLastPasswordChange.
     * @param value value to set the WMS_LAST_PASSWORD_CHANGE
     */
    public void setWmsLastPasswordChange(Timestamp value) {
        setAttributeInternal(WMSLASTPASSWORDCHANGE, value);
    }

    /**
     * Gets the attribute value for WMS_BLOCK using the alias name WmsBlock.
     * @return the WMS_BLOCK
     */
    public String getWmsBlock() {
        return (String) getAttributeInternal(WMSBLOCK);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_BLOCK using the alias name WmsBlock.
     * @param value value to set the WMS_BLOCK
     */
    public void setWmsBlock(String value) {
        setAttributeInternal(WMSBLOCK, value);
    }

    /**
     * Gets the attribute value for WMS_STATUS using the alias name WmsStatus.
     * @return the WMS_STATUS
     */
    public String getWmsStatus() {
        return (String) getAttributeInternal(WMSSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_STATUS using the alias name WmsStatus.
     * @param value value to set the WMS_STATUS
     */
    public void setWmsStatus(String value) {
        setAttributeInternal(WMSSTATUS, value);
    }

    /**
     * Gets the attribute value for WMS_STATUS_CDATE using the alias name WmsStatusCdate.
     * @return the WMS_STATUS_CDATE
     */
    public Timestamp getWmsStatusCdate() {
        return (Timestamp) getAttributeInternal(WMSSTATUSCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_STATUS_CDATE using the alias name WmsStatusCdate.
     * @param value value to set the WMS_STATUS_CDATE
     */
    public void setWmsStatusCdate(Timestamp value) {
        setAttributeInternal(WMSSTATUSCDATE, value);
    }

    /**
     * Gets the attribute value for WMS_REMARKS using the alias name WmsRemarks.
     * @return the WMS_REMARKS
     */
    public String getWmsRemarks() {
        return (String) getAttributeInternal(WMSREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_REMARKS using the alias name WmsRemarks.
     * @param value value to set the WMS_REMARKS
     */
    public void setWmsRemarks(String value) {
        setAttributeInternal(WMSREMARKS, value);
    }

    /**
     * Gets the attribute value for WMS_ENTER_UID using the alias name WmsEnterUid.
     * @return the WMS_ENTER_UID
     */
    public String getWmsEnterUid() {
        return (String) getAttributeInternal(WMSENTERUID);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_ENTER_UID using the alias name WmsEnterUid.
     * @param value value to set the WMS_ENTER_UID
     */
    public void setWmsEnterUid(String value) {
        setAttributeInternal(WMSENTERUID, value);
    }

    /**
     * Gets the attribute value for WMS_ENTER_FPC using the alias name WmsEnterFpc.
     * @return the WMS_ENTER_FPC
     */
    public String getWmsEnterFpc() {
        return (String) getAttributeInternal(WMSENTERFPC);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_ENTER_FPC using the alias name WmsEnterFpc.
     * @param value value to set the WMS_ENTER_FPC
     */
    public void setWmsEnterFpc(String value) {
        setAttributeInternal(WMSENTERFPC, value);
    }

    /**
     * Gets the attribute value for WMS_ENTER_DATE using the alias name WmsEnterDate.
     * @return the WMS_ENTER_DATE
     */
    public Timestamp getWmsEnterDate() {
        return (Timestamp) getAttributeInternal(WMSENTERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_ENTER_DATE using the alias name WmsEnterDate.
     * @param value value to set the WMS_ENTER_DATE
     */
    public void setWmsEnterDate(Timestamp value) {
        setAttributeInternal(WMSENTERDATE, value);
    }

    /**
     * Gets the attribute value for WMS_LAST_UPDATE_UID using the alias name WmsLastUpdateUid.
     * @return the WMS_LAST_UPDATE_UID
     */
    public String getWmsLastUpdateUid() {
        return (String) getAttributeInternal(WMSLASTUPDATEUID);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_LAST_UPDATE_UID using the alias name WmsLastUpdateUid.
     * @param value value to set the WMS_LAST_UPDATE_UID
     */
    public void setWmsLastUpdateUid(String value) {
        setAttributeInternal(WMSLASTUPDATEUID, value);
    }

    /**
     * Gets the attribute value for WMS_LAST_FPC using the alias name WmsLastFpc.
     * @return the WMS_LAST_FPC
     */
    public String getWmsLastFpc() {
        return (String) getAttributeInternal(WMSLASTFPC);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_LAST_FPC using the alias name WmsLastFpc.
     * @param value value to set the WMS_LAST_FPC
     */
    public void setWmsLastFpc(String value) {
        setAttributeInternal(WMSLASTFPC, value);
    }

    /**
     * Gets the attribute value for WMS_LAST_UPDATE_DATE using the alias name WmsLastUpdateDate.
     * @return the WMS_LAST_UPDATE_DATE
     */
    public Timestamp getWmsLastUpdateDate() {
        return (Timestamp) getAttributeInternal(WMSLASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_LAST_UPDATE_DATE using the alias name WmsLastUpdateDate.
     * @param value value to set the WMS_LAST_UPDATE_DATE
     */
    public void setWmsLastUpdateDate(Timestamp value) {
        setAttributeInternal(WMSLASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for WMS_APPROVE_UID using the alias name WmsApproveUid.
     * @return the WMS_APPROVE_UID
     */
    public String getWmsApproveUid() {
        return (String) getAttributeInternal(WMSAPPROVEUID);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_APPROVE_UID using the alias name WmsApproveUid.
     * @param value value to set the WMS_APPROVE_UID
     */
    public void setWmsApproveUid(String value) {
        setAttributeInternal(WMSAPPROVEUID, value);
    }

    /**
     * Gets the attribute value for WMS_APPROVE_FPC using the alias name WmsApproveFpc.
     * @return the WMS_APPROVE_FPC
     */
    public String getWmsApproveFpc() {
        return (String) getAttributeInternal(WMSAPPROVEFPC);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_APPROVE_FPC using the alias name WmsApproveFpc.
     * @param value value to set the WMS_APPROVE_FPC
     */
    public void setWmsApproveFpc(String value) {
        setAttributeInternal(WMSAPPROVEFPC, value);
    }

    /**
     * Gets the attribute value for WMS_APPROVE_DATE using the alias name WmsApproveDate.
     * @return the WMS_APPROVE_DATE
     */
    public Timestamp getWmsApproveDate() {
        return (Timestamp) getAttributeInternal(WMSAPPROVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_APPROVE_DATE using the alias name WmsApproveDate.
     * @param value value to set the WMS_APPROVE_DATE
     */
    public void setWmsApproveDate(Timestamp value) {
        setAttributeInternal(WMSAPPROVEDATE, value);
    }

    /**
     * Gets the attribute value for WMS_COMMENTS using the alias name WmsComments.
     * @return the WMS_COMMENTS
     */
    public String getWmsComments() {
        return (String) getAttributeInternal(WMSCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_COMMENTS using the alias name WmsComments.
     * @param value value to set the WMS_COMMENTS
     */
    public void setWmsComments(String value) {
        setAttributeInternal(WMSCOMMENTS, value);
    }

    /**
     * Gets the attribute value for WMS_EMAIL using the alias name WmsEmail.
     * @return the WMS_EMAIL
     */
    public String getWmsEmail() {
        return (String) getAttributeInternal(WMSEMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_EMAIL using the alias name WmsEmail.
     * @param value value to set the WMS_EMAIL
     */
    public void setWmsEmail(String value) {
        setAttributeInternal(WMSEMAIL, value);
    }

    /**
     * Gets the attribute value for WMS_COMP_ID using the alias name WmsCompId.
     * @return the WMS_COMP_ID
     */
    public Integer getWmsCompId() {
        return (Integer) getAttributeInternal(WMSCOMPID);
    }

    /**
     * Sets <code>value</code> as attribute value for WMS_COMP_ID using the alias name WmsCompId.
     * @param value value to set the WMS_COMP_ID
     */
    public void setWmsCompId(Integer value) {
        setAttributeInternal(WMSCOMPID, value);
    }
}

