package com.ciobera.fwms.trading.model.vo.readonly;

import com.ciobera.fwms.trading.model.vo.readonly.common.FWMSDHoldingAllVO;

import java.util.HashMap;
import java.util.Map;

import oracle.jbo.server.ViewObjectImpl;

import org.codehaus.groovy.runtime.InvokerHelper;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 11 00:25:06 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSDHoldingAllVOImpl extends ViewObjectImpl implements FWMSDHoldingAllVO {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSDHoldingAllVOImpl() {
    }
    
    private class AgrFuncHelper extends HashMap
      {
        private String funcName;

        public AgrFuncHelper(String funcName) 
        {
          super();
          this.funcName = funcName;  
        }


        public Object get(Object key) 
        {
          //Invoke private method
          //of our DefaultRowSet (sum,count,avg,min,max)
          //key is argument expression for the aggr funcion being called
          //sum("Salary")

          return InvokerHelper.invokeMethod(getDefaultRowSet(), funcName, key);
        }

      }
    
    public Map getSum() 
     {
       return new AgrFuncHelper("sum");
     }
     
     public Map getCount() 
     {
       return new AgrFuncHelper("count");
     }
}

