package com.ciobera.fwms.trading.model.vo.readonly;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 08 21:38:16 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSDHoldingAllVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FhaUserid,
        FhaFund,
        FhaFname,
        FhaCashB,
        FhaMvB,
        FhaNavB,
        FhaNavNavD,
        FhaNavNavDp,
        FhaNavNavW,
        FhaNavNavWp,
        FhaNavNavM,
        FhaNavNavMp,
        FhaNavNavY,
        FhaNavNavYp,
        FhaNavNavYtd,
        FhaNavNavYtdp;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FHAUSERID = AttributesEnum.FhaUserid.index();
    public static final int FHAFUND = AttributesEnum.FhaFund.index();
    public static final int FHAFNAME = AttributesEnum.FhaFname.index();
    public static final int FHACASHB = AttributesEnum.FhaCashB.index();
    public static final int FHAMVB = AttributesEnum.FhaMvB.index();
    public static final int FHANAVB = AttributesEnum.FhaNavB.index();
    public static final int FHANAVNAVD = AttributesEnum.FhaNavNavD.index();
    public static final int FHANAVNAVDP = AttributesEnum.FhaNavNavDp.index();
    public static final int FHANAVNAVW = AttributesEnum.FhaNavNavW.index();
    public static final int FHANAVNAVWP = AttributesEnum.FhaNavNavWp.index();
    public static final int FHANAVNAVM = AttributesEnum.FhaNavNavM.index();
    public static final int FHANAVNAVMP = AttributesEnum.FhaNavNavMp.index();
    public static final int FHANAVNAVY = AttributesEnum.FhaNavNavY.index();
    public static final int FHANAVNAVYP = AttributesEnum.FhaNavNavYp.index();
    public static final int FHANAVNAVYTD = AttributesEnum.FhaNavNavYtd.index();
    public static final int FHANAVNAVYTDP = AttributesEnum.FhaNavNavYtdp.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FWMSDHoldingAllVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute FhaUserid.
     * @return the FhaUserid
     */
    public String getFhaUserid() {
        return (String) getAttributeInternal(FHAUSERID);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaFund.
     * @return the FhaFund
     */
    public Long getFhaFund() {
        return (Long) getAttributeInternal(FHAFUND);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaFname.
     * @return the FhaFname
     */
    public String getFhaFname() {
        return (String) getAttributeInternal(FHAFNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaCashB.
     * @return the FhaCashB
     */
    public BigDecimal getFhaCashB() {
        return (BigDecimal) getAttributeInternal(FHACASHB);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaMvB.
     * @return the FhaMvB
     */
    public BigDecimal getFhaMvB() {
        return (BigDecimal) getAttributeInternal(FHAMVB);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavB.
     * @return the FhaNavB
     */
    public BigDecimal getFhaNavB() {
        return (BigDecimal) getAttributeInternal(FHANAVB);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavD.
     * @return the FhaNavNavD
     */
    public BigDecimal getFhaNavNavD() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVD);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavDp.
     * @return the FhaNavNavDp
     */
    public BigDecimal getFhaNavNavDp() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVDP);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavW.
     * @return the FhaNavNavW
     */
    public BigDecimal getFhaNavNavW() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVW);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavWp.
     * @return the FhaNavNavWp
     */
    public BigDecimal getFhaNavNavWp() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVWP);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavM.
     * @return the FhaNavNavM
     */
    public BigDecimal getFhaNavNavM() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVM);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavMp.
     * @return the FhaNavNavMp
     */
    public BigDecimal getFhaNavNavMp() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVMP);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavY.
     * @return the FhaNavNavY
     */
    public BigDecimal getFhaNavNavY() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVY);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavYp.
     * @return the FhaNavNavYp
     */
    public BigDecimal getFhaNavNavYp() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVYP);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavYtd.
     * @return the FhaNavNavYtd
     */
    public BigDecimal getFhaNavNavYtd() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVYTD);
    }

    /**
     * Gets the attribute value for the calculated attribute FhaNavNavYtdp.
     * @return the FhaNavNavYtdp
     */
    public BigDecimal getFhaNavNavYtdp() {
        return (BigDecimal) getAttributeInternal(FHANAVNAVYTDP);
    }
}

