package com.ciobera.fwms.trading.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 08 21:38:16 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSDHoldingAllVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSDHoldingAllVOImpl() {
    }

    /**
     * Returns the bind variable value for pLoggedInUserId.
     * @return bind variable value for pLoggedInUserId
     */
    public String getpLoggedInUserId() {
        return (String) getNamedWhereClauseParam("pLoggedInUserId");
    }

    /**
     * Sets <code>value</code> for bind variable pLoggedInUserId.
     * @param value value to bind as pLoggedInUserId
     */
    public void setpLoggedInUserId(String value) {
        setNamedWhereClauseParam("pLoggedInUserId", value);
    }
}

