package com.ciobera.fwms.trading.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 02 14:10:45 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSDHoldingAllVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSDHoldingAllVOImpl() {
    }
}

