package com.ciobera.fwms.system.model.vo;

import com.ciobera.fwms.system.model.vo.common.FWMSProductVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 15:05:50 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FWMSProductVOImpl extends ViewObjectImpl implements FWMSProductVO {
    /**
     * This is the default constructor (do not remove).
     */
    public FWMSProductVOImpl() {
    }
    
    

}

