package com.ciobera.fwms.system.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 00:37:15 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CurrencyVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CurrencyVOImpl() {
    }
}

