package com.ciobera.fwms.system.model.vo.readonly;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 00:37:15 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CurrencyVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WmsCurrencyId,
        WmsCurrencyDesc,
        WmsShortDesc;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int WMSCURRENCYID = AttributesEnum.WmsCurrencyId.index();
    public static final int WMSCURRENCYDESC = AttributesEnum.WmsCurrencyDesc.index();
    public static final int WMSSHORTDESC = AttributesEnum.WmsShortDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CurrencyVORowImpl() {
    }
}

