package com.ciobera.fwms.system.model.vo.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 26 16:31:03 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductIdSeqImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductIdSeqImpl() {
    }
}

